### ISSUE TITLE
Outstanding GCB migration tasks

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#10819]
This is a collection of still-outstanding tasks that need doing after the migration to google cloud build

- [ ] Run kubernetes tests after merge
- [ ] Darwin builder 
- [ ] Backport log uploads to v8, v7
- [ ] Decouple GCB secret handling (See gravitational/ops#327)
- [ ] Replace testing "constants" with proper configuration (See #8913)
- [ ] Revisit use of sommand-line Git in `teleport.e` checkout script (See gravitational/teleport.e#364)
- [x] Get rid of `etcd` spew in test logs

**Comment by zmb3** [comment]
Should we add GCB integration to gravitational/webapps as well?

**Comment by r0mant** [comment]
This is no longer relevant as we've switched to Github Actions.
