### ISSUE TITLE
Resource Access Requests

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10887]
Implement resource access requests, allowing users with appropriate permissions to search for resources they want to access, without requiring them to know which roles provide this access or which users are required to approve the request.

Tasks:
- [x] extend roles for search with `search_as_roles` #11836
- [x] `tsh request search` support #11836
- [x] `tsh request create --resources` support #12307
- [x] extend user ssh and TLS certs to include allowed resource IDs #12494
- [x] enforce resource restrictions based on allowed resource IDs in cert #12651
- [x] automatic resource requests for `tsh ssh`
   - [x] #13051
   - [x] #13326
   - [x] #13323
- [x] search-based access requests from Web UI https://github.com/gravitational/webapps.e/pull/301
- [x] write docs #13831

**Comment by jeffery-jen** [comment]
upvote

**Comment by nklaassen** [comment]
Closing as all tasks here are completed and merged to master and branch/v10, this feature will be released with 10.0. Docs can be found at https://goteleport.com/docs/ver/10.0/enterprise/workflow/resource-requests/

Pending improvements have separate issues:
- https://github.com/gravitational/teleport/issues/13897
- https://github.com/gravitational/teleport/issues/13940
