### ISSUE TITLE
Desktop Access File System Sharing Tracking issue

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#12274]
RFD: https://github.com/gravitational/teleport/pull/12103

## New TDP Messages

Frontend primarily means [`codec.ts`](https://github.com/gravitational/webapps/blob/master/packages/teleport/src/lib/tdp/codec.ts), backend [`proto.go`](https://github.com/gravitational/teleport/blob/master/lib/srv/desktop/tdp/proto.go)

#### `Shared Directory Announce`
- [x] frontend
- [x] backend

#### `Shared Directory Acknowledge`
- [x] frontend
- [x] backend

#### `Shared Directory Info Request`
- [x] frontend
- [x] backend

#### `Shared Directory Info Response`
- [x] frontend
- [x] backend

#### `Shared Directory Create Request`
- [x] frontend
- [x] backend

#### `Shared Directory Create Response`
- [x] frontend
- [x] backend

#### `Shared Directory Delete Request`
- [x] frontend
- [x] backend

#### `Shared Directory Delete Response`
- [x] frontend
- [x] backend

#### `Shared Directory Read Request`
- [x] frontend
- [x] backend

#### `Shared Directory Read Response`
- [x] frontend
- [x] backend

#### `Shared Directory Write Request`
- [x] frontend
- [x] backend

#### `Shared Directory Write Response`
- [x] frontend
- [x] backend

#### `Shared Directory Move Request`
- [x] frontend
- [x] backend

#### `Shared Directory Move Response`
- [x] frontend
- [x] backend

#### `Shared Directory List Request`
- [x] frontend
- [x] backend

#### `Shared Directory List Response`
- [x] frontend
- [x] backend

## RDP <--> TDP translation

This happens primarily in the rust library, categorized here by RDP message type:

- [x] `IRP_MJ_CREATE`
- [x] `IRP_MJ_CLOSE`
- [x] `IRP_MJ_READ`
- [x] `IRP_MJ_WRITE `
- [x] `IRP_MJ_QUERY_INFORMATION`
- [x] `IRP_MJ_SET_INFORMATION`
- [x] `IRP_MJ_DIRECTORY_CONTROL`
    - [x] missing some additional `file_info_class`es https://github.com/gravitational/teleport/blob/c16724b1ab18d5dccbe7061dbe1fa7239d1f9dfe/lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs#L3581
- [x] `IRP_MJ_LOCK_CONTROL`
- [x] `IRP_MJ_QUERY_VOLUME_INFORMATION`
    - [x] missing some additional `file_info_class`es https://github.com/gravitational/teleport/blob/c16724b1ab18d5dccbe7061dbe1fa7239d1f9dfe/lib/srv/desktop/rdp/rdpclient/src/rdpdr/mod.rs#L1030
- [x] `IRP_MJ_DEVICE_CONTROL`
- [x] `IRP_MJ_SET_VOLUME_INFORMATION` ([not actually supported by FreeRDP](https://github.com/FreeRDP/FreeRDP/blob/dfa231c0a55b005af775b833f92f6bcd30363d77/channels/drive/client/drive_main.c#L700-L746))

## Client UI

TODO

## RBAC
- [x] design
- [x] implementation
- [x] documentation

**Comment by ubmaity** [comment]
Any updates on this? when can we expect directory upload/download feature ?

**Comment by RyanCode** [comment]
How's it going now

**Comment by ibeckermayer** [comment]
@ubmaity @RyanCode we're planning on releasing this feature in "preview" mode in Teleport 10.2, which we're aiming to release on Friday (give or take).

**Comment by ibeckermayer** [comment]
Heads up we just bumped it to next Friday.

**Comment by RyanCode** [comment]
> Heads up we just bumped it to next Friday.

goog job!
