### ISSUE TITLE
Database Access Roadmap 2022 Q2

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#12704]
Database Access Roadmap for Q2 2022

- [ ] GCP
    - [ ] #12701
    - [ ] #12700:
    - [ ] #12705: 
        - [ ] MySQL
        - [ ] Postgres
        - [ ] SQLServer
        - [ ] Memorystore/Redis 
   - [ ]  #12698
       - [ ] Active Directory
       - [ ] Password Rotation
    - [ ] GCP access _(Low-Priority)_
        - [ ] tsh gcloud wrapper 
        - [ ] web console access  
     - [ ] GCP native databases support  _(Low-Priority)_
        - [ ] Firestore/Datastore 
        - [ ] BigQuery  
        - [ ] Spanner  
- [ ] New DB protocols: 
    - [x] #7482
    - [x] #6840
- [ ] Other:
    - [x] #12341
    - [x] gravitational/cloud#1325
    - [x] #12538
    - [x] #12146

**Comment by ravicious** [comment]
I was about to ask what are the plans regarding adding MFA support to `tsh proxy db --tunnel` just so that we can coordinate this better, but I managed to find this roadmap in time. ;)

We also plan to add per-session MFA support to Connect in Q2, so we'll wait for #12538 first.

In the meantime I'm going to work on adding an equivalent of `client.RetryWithRelogin` to Connect, which should work similar to per-session MFA in terms of tsh daemon <=> Connect communication.

**Comment by zmb3** [comment]
@smallinsky I assume our plans changed and this is no longer an accurate roadmap. Can we close the issue?
