### ISSUE TITLE
Recording Proxy

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1327]
To allow recording of sessions with OpenSSH clients, we need to enable recording at the proxy instead of at the node. To do this this, we'll need to terminate session at the proxy, build a connection to the destination node, and record and forward traffic.

Work on the recording proxy will be broken up into the following parts.

- [x] #1329: Create a resource for Cluster Configuration.
  - [x] Cluster Configuration resource.
  - [x] Disable session recording.
- [x] #1441: Proxy should only have `VerbCreate` access to `KindHostCA` in recording mode.
- [x] #1429: Improve Web UI error messages when session recording is disabled.
- [x] #1446: Re-factor `lib/srv` to create interfaces for request types to support local and remote execution.
- [x] #1452: Fix existing issues with agent forwarding.
- [x] #1000: Agent forwarding support in the Web UI and `tsh`.
- [x] #1458: Update `tctl` to support generating a host certificate.
- [x] #1343: Re-name Teleport environment variables.
- [x] #1481: Implement a forwarding server.
- [x] #1494: Update `reversetunnel` local and remote sites.
- [x] #1496: Recording Proxy test coverage.
- [x] #1497: Documentation on how to use the new recording proxy.

**Comment by kontsevoy** [comment]
Closing, since thedocs are in a separate tickets.
