### ISSUE TITLE
RFD 73: Tracking ticket

### ISSUE THREAD

**Issue by logand22** [gravitational/teleport#13825]
Tracking ticket for migrating to Amazon ECR from Quay.io.

Will be focusing on a per Github Repository basis as a lot of the publishing work for the different image repositories can be done together. 

## Teleport
- [ ] ECR Infrastructure
- [ ] Publish to both Quay.io and ECR
- [ ] Mirror existing repositories
- [ ] Promote to both Quay.io and ECR public
- [ ] Update documentation 
- [ ] Update testing and dependent locations (Cloud uses quay.io teleport image)

## Teleport Plugins
- [ ] ECR Infrastructure https://github.com/gravitational/cloud-terraform/pull/662
- [ ] Publish to both Quay.io and ECR
- [ ] Mirror existing repositories
- [ ] Promote to both Quay.io and ECR public
- [ ] Update documentation
- [ ] Update any testing and dependent locations

Will add more sections as the above wrap up.
