### ISSUE TITLE
Machine ID Github Actions Epic

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#14291]
Users should be able to easily leverage `tbot` within Github Actions workflows to access resources protected by teleport. This may be used for deployment purposes (e.g rolling out database migrations, or SCPing files to a host).

This is currently possible by creating a bot token and storing it as a Github Actions secret, but this isn't ideal as this token is vulnerable to exfiltration by untrusted code running in CI workflows.

This work can be broken down into a couple pieces of work:

- [x] #14293. It may be useful to look at existing cloud providers that implement this functionality (e.g https://github.com/google-github-actions/auth). 
- [x] #16796 .
- [ ] Produce guide to demonstrate using Github Actions, Machine ID and Kube Access or Server Access.
- [ ] Contact GH and see if we can get documentation on their site as Vault and GCP have.

**Comment by russjones** [comment]
Support CI/CD Platform support (Gitlab, GitHub, and CircleCI, Google Cloud Build)
[Support GitHub actions (join via OIDC), including new guides](https://github.com/gravitational/teleport/issues/14291) (w/ Azure DevOps if free)

**Comment by strideynet** [comment]
https://github.com/gravitational/teleport/issues/16994
