### ISSUE TITLE
Database Access Roadmap 2022 Q3

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#14566]
Database Access Roadmap for Q3 2022

- **Microsoft Azure**:
  - [ ]  DB Auto Discovery:
     - [x] #14688
     - [x] SQLServer
     - [ ] [Azure Cosmos DB](https://azure.microsoft.com/en-us/services/cosmos-db/)
        - [ ] MongoDB
        - [ ] Cassandra
     - [x] #16062 
  - [ ] Databases Access:
     - [x] #10485
     - [x] #8621
     - [ ] #8558
     - [ ] #14567
   - [ ] #11780
       - [x] #16401

- [ ] **New DB Protocols**: 
   - [x] #7482
   - [x] #6840

- [ ] **Other items**: 
  - [ ] SQLServer improvements:
     - [x] #13837
     - [ ] #14741
  - [x] #12538
  - [ ] #12404
  - [ ] ~~#13727~~ 
  - [x] #14369
  - [x] gravitational/cloud#1325
  - [ ] interactive `teleport db configure`. 

- [ ] AWS (Optional): 
  - [x] #9820
  - [x] #10550

- [ ] GCP (Optional):
    - [ ] #12698

**Comment by zmb3** [comment]
@smallinsky we're long past Q322, can we close this one?
