### ISSUE TITLE
Support newer terraform version

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#15087]
### What would you like Teleport to do?

Support new versions of terraform

When following the docs I read that I can download and use Terraform >= 0.12. The link makes me download Terraform 1.2.6, the next command fails because the condition in `provider.tf` refuses versions like 1.X.Y. This makes little sense as there is no breaking change between 1.0.0 and 0.15.5, and all v1 Terraform versions should now be stable and backward compatible with 1.0.0 (and 0.15.5, which we are allowing).

### What problem does this solve?

Time to value, especially as installing old Terraform versions is a pain. Avoid customers to install antique TF versions for us. 

### If a workaround exists, please include it.

Do not use package manager to install terraform and craft download URL manually to download terraform.

### ToDo:

- [ ] Validate the terraform HA AWS works with 0.15.5 and 1.2.6
- [ ] Update documentation to reflect real TF constraints (0.12 does not work)
- [ ] Lift version restriction and allow 1.X versions
