### ISSUE TITLE
Smartcard testing meta issue

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#16502]
`IoctlCodes` to write tests for:

- [x] `IoctlCode::SCARD_IOCTL_ACCESSSTARTEDEVENT`
- [x] `IoctlCode::SCARD_IOCTL_ESTABLISHCONTEXT`
- [x] `IoctlCode::SCARD_IOCTL_RELEASECONTEXT`
- [ ] `IoctlCode::SCARD_IOCTL_CANCEL`
- [x] `IoctlCode::SCARD_IOCTL_ISVALIDCONTEXT`
- [x] `IoctlCode::SCARD_IOCTL_LISTREADERSW`
- [x] `IoctlCode::SCARD_IOCTL_GETSTATUSCHANGEW`
- [x] `IoctlCode::SCARD_IOCTL_CONNECTW`
- [x] `IoctlCode::SCARD_IOCTL_DISCONNECT`
- [x] `IoctlCode::SCARD_IOCTL_BEGINTRANSACTION`
- [x] `IoctlCode::SCARD_IOCTL_ENDTRANSACTION`
- [ ] `IoctlCode::SCARD_IOCTL_STATUSA`
- [x] `IoctlCode::SCARD_IOCTL_STATUSW`
- [x] `IoctlCode::SCARD_IOCTL_TRANSMIT`
- [x] `IoctlCode::SCARD_IOCTL_GETDEVICETYPEID`
- [x] `IoctlCode::SCARD_IOCTL_READCACHEW`
- [x] `IoctlCode::SCARD_IOCTL_WRITECACHEW`
- [x] `IoctlCode::SCARD_IOCTL_GETREADERICON`

**Comment by zmb3** [comment]
@ibeckermayer anything left to do here?
