### ISSUE TITLE
Predicate RBAC Server Access Integration Tracker

### ISSUE THREAD

**Issue by xacrimon** [gravitational/teleport#18209]
This issue tracks integrating the predicate RBAC into Teleport Server Access. Progress is tracked on the `dev-predicate` 
branch for now.

cc @klizhentas for visibility.

- [x] Implement `AccessPolicy` resource
- [x] Implement RBAC engine @xacrimon  https://github.com/gravitational/teleport/pull/17700
- [ ] RBAC engine integration for resources, session start, session join (no options) @xacrimon  https://github.com/gravitational/teleport/pull/18020 and https://github.com/gravitational/predicate-lang/pull/24
- [ ] Implement predicate-lang primitives for moderated sessions & joining https://github.com/gravitational/predicate-lang/pull/26 @vitorenesduarte 
- [ ] Integrate `StartSession` and `JoinSession` into RBAC checks @xacrimon 
- [ ] Policy mapping @xacrimon 
- [ ] Integrate with possible role options, add option solver (@vitorenesduarte)
- [ ] Access requests? @xacrimon
