### ISSUE TITLE
Improving Passkey Support

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#19314]
```[tasklist]
### Tasks (in order of priority)
- [ ] https://github.com/gravitational/teleport/issues/31350
- [ ] https://github.com/gravitational/teleport/issues/36233
- [ ] https://github.com/gravitational/teleport/issues/37616
- [ ] https://github.com/gravitational/teleport/issues/36232
- [ ] https://github.com/gravitational/teleport/issues/37622
- [ ] https://github.com/gravitational/teleport/issues/36234
- [ ] https://github.com/gravitational/teleport/issues/37615
- [ ] https://github.com/gravitational/teleport/issues/38433
```

**Comment by codingllama** [comment]
Some interesting web-specific advice here, including auto-fill, "upselling" logins, etc: https://passkeys.dev/docs/use-cases/bootstrapping/. All interesting to consider.

**Comment by twakes** [comment]
I have also noticed that you can not log into Teleport Connect as Connect expects a hardware security token (see attached screenshot). Using the fingerprint reader does not work. This also breaks the flow for Connect My Computer since that requires the use of Teleport Connect.

So the onboarding flow for Connect My Computer (which I think was created to show fast time to value) does not work if you use passwordless login.

![Screenshot 2023-12-14 at 11 30 42 AM](https://github.com/gravitational/teleport/assets/3769197/29aba662-d4e9-4035-9a52-a25c9656c7a0)

**Comment by codingllama** [comment]
FYI @ravicious, see Taylor's comment above.

**Comment by ravicious** [comment]
I'm not familiar with how macOS passkeys support interacts with Touch ID and our auth. However, doesn't the problem described by @twakes boil down to [Touch ID being scoped by application](https://goteleport.com/docs/access-controls/guides/passwordless/#registering-touch-id-for-tsh)?  If you add a passwordless Touch ID device to your Teleport account through a browser, you cannot use this device to log in through tsh or Connect.

It's still an UX issue, but it's not unique to Connect. Well, it's two issues:

1. The UI in Connect focuses on hardware keys, just as this GitHub issue describes.
2. Touch ID registrations are scoped per app and we don't have a good way of handling that for the user. Currently, the user needs to know that this is the case and they need to register a Touch ID device through a browser and through tsh.

See also #35770 that I just created, the passwordless docs should explain how Connect interacts with Touch ID.

**Comment by codingllama** [comment]
There's really no way around the per-app limitation for the credentials, that's baked into macOS' security model. Using the "modern" version of macOS passkeys could solve it, but sadly it's gated behind APIs we can't use either (as they require an explicit associated domain, and we can't do that because of on-prem installs). We could do some of it for Cloud, but not on-prem.

@ravicious thanks for taking a look and for the insights.

@twakes, did you register your passwordless credential directly in the browser, using touch ID? Have you tried the same flow using a Yubikey (or similar) as the passwordless authenticator?

**Comment by twakes** [comment]
did you register your passwordless credential directly in the browser,
using touch ID?

> yes

Have you tried the same flow using a Yubikey (or similar) as the
passwordless authenticator?

> no

If using Touch ID breaks a lot of UX, perhaps we don’t allow for it?

**Comment by codingllama** [comment]
> If using Touch ID breaks a lot of UX, perhaps we don’t allow for it?

Finding out what kind of authenticator is used ranges from difficult to impossible depending on cluster settings. Cluster admins could forbid Touch ID using attestation settings, although many other authenticators might end up being blocked in process.

This is in a way the root of the problem, as we often can't say if the user has only Touch ID, so it makes it difficult to show a good error message. Adding to that, if the user isn't authenticated yet we shouldn't leak anything about what MFA devices they have. We could, based on cluster settings (specifically "connector=passwordless"), make an educated guess about the problem, but that won't catch all cases.

Forbidding Touch ID also feels bad, as it is very practical and has good security properties. I don't have any great suggestions at the ready, but my gut is that we should figure out a way to show better errors or somehow make it work.

**Comment by twakes** [comment]
Forbidding Touch ID also feels bad, as it is very practical and has good security properties. I don't have any great suggestions at the ready, but my gut is that we should figure out a way to show better errors or somehow make it work.

> I agree

**Comment by OskyEdz** [comment]
My passkey manager (Bitwarden) supports adding, removing and verifying it's passkey. But it does not support logging in with that passkey manager.

What I mean is that when adding a passkey Teleports first prompts the browser for any available passkey managers, where Bitwarden responds. But when it comes to accually log in to Teleport it will skip/fail to prompt Bitwarden and go for Windows Hello/Hardware keys.

Teleport version: 15.0.2
Bitwarden version: 2024.2.0

**Comment by codingllama** [comment]
@OskyEdz I don't think there's much we can do here, it sounds like this is all browser behavior. You can check https://webauthn.io/ and see if you can repro the problem there, if you can then I suggest opening an issue in your browser of choice (or even Bitwarden itself).

**Comment by OskyEdz** [comment]
@codingllama I'm mostly confronting to there being a difference in the code between the Teleport login screen and the account setup options screen for MFA's and Passkeys. 

There also seam to be a more overall issues with browser extension passkeys. 

The way it is done on the login screen might be the most secure way and it works on the settings page because it is an internal page and does not need all the bells for detecting attacks.

**Comment by naimo84** [comment]
> @codingllama I'm mostly confronting to there being a difference in the code between the Teleport login screen and the account setup options screen for MFA's and Passkeys.

I can second this. For me passkey is working on the options Screen, but not in the login page

**Comment by codingllama** [comment]
@OskyEdz or @naimo84, could you please open a bug report for your problem and add as much detail as you can, in particular reproduction steps? I just ran some tests but it looks alright to me.

https://github.com/gravitational/teleport/issues/new?assignees=&labels=bug&projects=&template=bug_report.md
