### ISSUE TITLE
Teleport Discover new RDS flow

### ISSUE THREAD

**Issue by ryanclark** [gravitational/teleport#21222]
This is an umbrella ticket to track Discover phases

### RFDs

```[tasklist]
### RFDs
- [ ] https://github.com/gravitational/teleport/pull/13440
- [ ] https://github.com/gravitational/teleport/pull/18546
- [ ] https://github.com/gravitational/teleport/pull/22556
```

### Day 1 (11.x)

```[tasklist]
### Day 1 Implementation
- [ ] https://github.com/gravitational/teleport/pull/20753
- [ ] https://github.com/gravitational/teleport/pull/20719
- [ ] https://github.com/gravitational/teleport/pull/21062
- [ ] https://github.com/gravitational/teleport/pull/19824
- [ ] https://github.com/gravitational/teleport/pull/19063
- [ ] https://github.com/gravitational/webapps/pull/1481
- [ ] https://github.com/gravitational/webapps/pull/1459
- [ ] https://github.com/gravitational/webapps/pull/1441
- [ ] https://github.com/gravitational/webapps/pull/1433
- [ ] https://github.com/gravitational/webapps/pull/1418
- [ ] https://github.com/gravitational/webapps/pull/1412
- [ ] https://github.com/gravitational/webapps/pull/1375
- [ ] https://github.com/gravitational/webapps/pull/1372
```

### Metrics (12.0)

```[tasklist]
### Metrics
- [ ] https://github.com/gravitational/teleport/pull/20925
- [ ] https://github.com/gravitational/teleport/pull/20207
- [ ] https://github.com/gravitational/teleport/pull/20581
- [ ] https://github.com/gravitational/cloud/pull/3127
- [ ] https://github.com/gravitational/cloud/pull/3289
- [ ] https://github.com/gravitational/cloud/pull/3328
```

### AWS Integration (13.0)

```[tasklist]
### AWS Integration
- [ ] https://github.com/gravitational/teleport/pull/20030
- [ ] https://github.com/gravitational/teleport/pull/21093
- [ ] https://github.com/gravitational/teleport/pull/23553
- [ ] https://github.com/gravitational/teleport/pull/23912
- [ ] https://github.com/gravitational/teleport/issues/22128
- [ ] https://github.com/gravitational/teleport/issues/22129
- [ ] https://github.com/gravitational/teleport/issues/22130
- [ ] https://github.com/gravitational/teleport/issues/22131
```

### Day 2 (13.2)

```[tasklist]
### Day 2
- [ ] https://github.com/gravitational/teleport/issues/22133
- [ ] https://github.com/gravitational/teleport/issues/22132
```

### 14

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/25494
```

**Comment by zmb3** [comment]
@kimlisa is this issue still accurate or has the day 2 stuff marked for 12.3 been completed?

**Comment by kimlisa** [comment]
@zmb3 updated

**Comment by marcoandredinis** [comment]
This is now completed
