### ISSUE TITLE
Agentless enrollment and discovery

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#21408]
```[tasklist]
## RFD
- [ ] https://github.com/gravitational/teleport/pull/18676
- [ ] https://github.com/gravitational/teleport/pull/19261
```

```[tasklist]
## 12.0.0
- [x] https://github.com/gravitational/teleport/pull/19648
- [x] https://github.com/gravitational/teleport/pull/20020
```

```[tasklist]
### 12.2.0
- [ ] https://github.com/gravitational/teleport/issues/18627
- [ ] https://github.com/gravitational/teleport/issues/17865
- [x] https://github.com/gravitational/teleport/issues/21406 https://github.com/gravitational/teleport/pull/21916
- [ ] https://github.com/gravitational/teleport/pull/21832
- [ ] https://github.com/gravitational/teleport/pull/22615
```

```[tasklist]
### 13.0.0
- [ ] https://github.com/gravitational/teleport/issues/18329
- [ ] https://github.com/gravitational/teleport/issues/20407
- [ ] https://github.com/gravitational/teleport/pull/21875
- [ ] https://github.com/gravitational/teleport/issues/24222
```

**Comment by zmb3** [comment]
@r0mant @lxea @capnspacehook v13 is long in the past, can someone take a fresh look at this issue and either update it with what's left or close it?

**Comment by r0mant** [comment]
Yeah I think we can close this.
