### ISSUE TITLE
Cloud automatic upgrades

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#21516]
## RFD

```[tasklist]
- [ ] https://github.com/gravitational/teleport/pull/20622
```

## 12.1

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/21492
- [ ] https://github.com/gravitational/teleport/issues/21952
- [ ] https://github.com/gravitational/teleport/issues/21951
```

Success criteria:
- Teleport Access Manager install script uses apt/deb repositories to install Teleport.

## 12.2

```[tasklist]
## Package repositories
- [ ] https://github.com/gravitational/teleport/issues/21447
- [ ] https://github.com/gravitational/teleport/issues/21863
- [ ] https://github.com/gravitational/teleport/issues/21864
- [ ] https://github.com/gravitational/teleport/issues/21999
```

Success criteria:
- Cloud customers can install Teleport from Cloud-specific repository along with the upgrade ticker.

## 13.0

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/22450
- [ ] https://github.com/gravitational/teleport/issues/22732
- [ ] https://github.com/gravitational/teleport/issues/22002
- [ ] https://github.com/gravitational/teleport/issues/22453
- [ ] https://github.com/gravitational/teleport/issues/22731
- [ ] https://github.com/gravitational/teleport/issues/23091
- [ ] https://github.com/gravitational/teleport/issues/22454
- [ ] https://github.com/gravitational/teleport/issues/22144
- [ ] https://github.com/gravitational/cloud/issues/3639
- [ ] https://github.com/gravitational/teleport/issues/24750
```

Success criteria:
- Systemd agents can upgrade automatically.
- Kubernetes agent can upgrade automatically.

## 13.1

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/22451
- [ ] https://github.com/gravitational/teleport/issues/26066
- [ ] https://github.com/gravitational/teleport/pull/24865
```

**Comment by zmb3** [comment]
@r0mant anything else we're tracking here, or good to close?
