### ISSUE TITLE
Headless SSO umbrella

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#21520]
```[tasklist]
## RFD
- [ ] https://github.com/gravitational/teleport/pull/21005
```
```[tasklist]
## Implementation status
- [ ] https://github.com/gravitational/teleport/issues/21519
```

```[tasklist]
## Related
- [ ] https://github.com/gravitational/teleport/issues/10923
- [ ] https://github.com/gravitational/teleport/issues/9127
- [ ] https://github.com/gravitational/teleport/issues/7838
```

**Comment by zmb3** [comment]
FYI, I also started putting the `headless-sso` label on issues, so there's a few more that aren't mentioned here: https://github.com/gravitational/teleport/issues?q=is%3Aopen+is%3Aissue+label%3Aheadless-sso
