### ISSUE TITLE
Improve Kubernetes Access performance/reliability

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#21613]
This is an umbrella ticket to track Kubernetes Access improvements :

```[tasklist]
### Tasks
- [x] https://github.com/gravitational/teleport/pull/22388
- [x] https://github.com/gravitational/teleport/pull/22308
- [ ] https://github.com/gravitational/teleport/issues/22598
- [ ] https://github.com/gravitational/teleport/issues/23763
- [ ] https://github.com/gravitational/teleport/issues/25539
- [ ] https://github.com/gravitational/teleport/issues/26426
- [ ] https://github.com/gravitational/teleport/issues/25540
- [ ] https://github.com/gravitational/teleport/issues/25541
- [ ] https://github.com/gravitational/teleport/issues/29362
```

**Comment by tigrato** [comment]
@rosstimothy we can close it. 
We also have https://github.com/gravitational/cloud/pull/5854 that never merged because there is no reviews
