### ISSUE TITLE
Azure - node joining/auto-discovery - umbrella ticket

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#21783]
```[tasklist]
### RFD
- [ ] https://github.com/gravitational/teleport/pull/16957
- [ ] https://github.com/gravitational/teleport/pull/19172
```

```[tasklist]
### Implementation (v12.1)
- [ ] https://github.com/gravitational/teleport/pull/21087
- [ ] https://github.com/gravitational/teleport/pull/20019
- [ ] https://github.com/gravitational/teleport/pull/17850
```

```[tasklist]
### Documentation and IaC
- [ ] https://github.com/gravitational/teleport/issues/22685
- [ ] https://github.com/gravitational/teleport/pull/21597
- [ ] https://github.com/gravitational/teleport/issues/21786
```

```[tasklist]
### Other bugs / docs
- [ ] #28838
- [ ] #28839
- [ ] #28879
- [ ] #28880
- [ ] #28881
- [ ] https://github.com/gravitational/teleport/issues/31602
- [ ] https://github.com/gravitational/teleport/issues/31758
- [ ] #29954
```

**Comment by zmb3** [comment]
Closing this tracking ticket. We can track the last couple of remaining items separately, but this project is largely completed.
