### ISSUE TITLE
Login Rules Tracker

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#21847]
## RFD

```[tasklist]
- [x] https://github.com/gravitational/teleport/blob/master/rfd/0078-login-rules.md
```

## Preview Release (11.3)

```[tasklist]
- [x] Login Rules for SSO users
- [x] https://github.com/gravitational/teleport/pull/21195
```

## Improvements

```[tasklist]
- [x] https://github.com/gravitational/teleport/issues/21326
- [ ] https://github.com/gravitational/teleport/issues/21840
- [ ] https://github.com/gravitational/teleport/issues/21849
- [x] https://github.com/gravitational/teleport/issues/20340
- [ ] https://github.com/gravitational/teleport/issues/21839
- [ ] https://github.com/gravitational/teleport/issues/23921
- [ ] Support `tctl login_rule` commands in OSS tctl
- [ ] https://github.com/gravitational/teleport/issues/26296
```
