### ISSUE TITLE
TLS Routing ALB Support for all protocols

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#21870]
This is an umbrella ticket to track TLS Routing ALB feature progress: 

### Phase 0 (Feb-Mar)

```[tasklist] 
### RFD 
- [ ] https://github.com/gravitational/teleport/issues/21869

```
### Phase 1 (12.1.x-12.2)

```[tasklist]
### Implementation Application Access
- [x] TLS routing through ALB for Application Access.
```

##### Success criteria:
Teleport support access behind  ALB for following protocols/cases:
- Application Access

### Phase 2 (13.0)

```[tasklist]
### Kubernetes Access 
- [X] TLS routing through ALB for Kubernetes Access.
```

Teleport support access behind  ALB for following protocols/cases:
- Kubernetes Access

### Phase 3 (13.0)

```[tasklist]
### Implementation Reverse Tunnel/Auth
- [x] TLS  routing through ALB for Reverse Tunnel.
- [x] Teleport Auth HTTP/gRPC communication.
```
##### Success criteria:
Teleport support access behind  ALB for following protocols/cases:
- Reverse Tunnel
- Teleport Auth protocols

### Phase 3.1 (13.0)

```[tasklist]
### Implementation Server
- [x] TLS routing through ALB for Server Access.
```
##### Success criteria:
Teleport support access behind  ALB for following protocols/cases:
- SSH Server Access

### Phase 4 (13.0)
```[tasklist] 
### IAM token joining  Support
- [ ] https://github.com/gravitational/teleport/issues/20792
```

##### Success criteria:
Teleport support access behind  ALB for following protocols/cases:
- IAM Joining

### Phase 5 (13.0)

```[tasklist]
### Dependency:
- [x] `tctl` flow
- [x] Teleport Plugins
- [x] Teleport Terraform provider
```

### Phase 6 (13.0)

```[tasklist]
### Post Items:
- [x] Release Preview
- [x] Teleport Could Testing
- [x] Documentation
```

### Phase 7 (13.3)

```[tasklist]
### Leftovers
- [x] Teleport **Connect**
- [x] Kube Access full support
- [ ] https://github.com/gravitational/teleport/issues/24711
- [ ] https://github.com/gravitational/teleport/issues/26836
- [ ] https://github.com/gravitational/teleport/issues/27044
- [ ] https://github.com/gravitational/teleport/issues/27397
- [x] Helm Charts Alignment
```

**Comment by greedy52** [comment]
Yet another protocol: SSH over grpc
https://github.com/gravitational/teleport/blob/master/rfd/0100-proxy-ssh-grpc.md

**Comment by greedy52** [comment]
Yet another client to update (kubesession):
https://github.com/gravitational/teleport/blob/master/lib/client/kubesession.go

**Comment by greedy52** [comment]
- Database Access - v10.2.4
- App Access - [v12.1.5](https://github.com/gravitational/teleport/releases/tag/v12.1.5)
- SSH Access, Teleport Agent - [v13.0.0](https://github.com/gravitational/teleport/releases/tag/v13.0.0)
- Kube Access
   - `tsh proxy kube` -  [v13.0.0](https://github.com/gravitational/teleport/releases/tag/v13.0.0)
   - `tsh kube join`/`tsh request search --kind=pod`  - [v13.0.2](https://github.com/gravitational/teleport/releases/tag/v13.0.2)
   - `tsh kubectl`/`tsh kube exec` [v13.0.4](https://github.com/gravitational/teleport/releases/tag/v13.0.4)
- IP Pinning and remote address logging (`proxy_service.trust_x_forwarded_for`) - [v13.2.0](https://github.com/gravitational/teleport/releases/tag/v13.2.0)
- Teleport Connect
  - General - [v13.0.2](https://github.com/gravitational/teleport/releases/tag/v13.0.2)
  - Kubernetes Access - v14.0.0
