### ISSUE TITLE
SQL Server Database Access Improvements

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#21873]
This is an umbrella ticket to track SQL Server improvements progress: 

### Phase 1 (Feb)

```[tasklist]
### Prerequisites:  
- [ ] https://github.com/gravitational/teleport/issues/12336
- [ ] https://github.com/gravitational/teleport-private/issues/184
```

### Phase 2 (12.2-12.3 / March-Apr)

```[tasklist]
### X509 PKINIT Support:
- [ ] https://github.com/gravitational/teleport/issues/13837
- [x] PKINIT x509 Documentation
```
#### Success Criteria:
- Teleport Database Access supports X.509 auth with SQL Server. 

### Phase 3  (12.3 / Apr)

```[tasklist]
### SQLServer RDS Proxy Support:
- [ ] https://github.com/gravitational/teleport/issues/17339
- [x] SQLSever RDS Documentation
```
#### Success Criteria:
- Users can connect to RDS Proxy SQL Server through Database Access.
