### ISSUE TITLE
Database Access AWS OpenSearch integration

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#21874]
This is an umbrella ticket to track DB Access AWS OpenSearch integration progress: 

### Phase 1 (Arp-May)

```[tasklist]
### OpenSearch CLI Database Access:
- [ ] https://github.com/gravitational/teleport/issues/21211
- [x] Documentation
```

#### Success Criteria:
- Teleport Database Access supports AWS OpenSearch CLI access.  

### Phase 2 (May)
```[tasklist]
### OpenSearch Dashboards Access:  
- [ ] https://github.com/gravitational/teleport/issues/32628
- [ ] Documentation
```

### Phase 3 (May)
```[tasklist]
### Auto Discovery:  
- [ ] https://github.com/gravitational/teleport/issues/26670
```

#### Success Criteria:
- Teleport Support OpenSearch Dashboards Access via Application Access or Database Access
