### ISSUE TITLE
Oracle Database Access Protocol Integration

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#21871]
This is an umbrella ticket to track Oracle Integration progress: 

### Phase 0 (Feb-Mar)

```[tasklist] 
### RFD 
- [ ] https://github.com/gravitational/teleport/pull/16435

```

### Phase 1 (Feb-Mar)

```[tasklist]
### Implementation 
- [ ] https://github.com/gravitational/teleport/issues/8064
```

#### Success Criteria: 
- Users can connect to Oracle database through Teleport
### Phase 2 (14.0-14.0.x)

```[tasklist]
### Implementation
- [x] Oracle Audit Logs support
- [ ] Teleport Connect alignment
```
#### Success Criteria: 
- Oracle Protocol is auditable via Teleport Audit Logs.

**Comment by zmb3** [comment]
@smallinsky good to close this one?
