### ISSUE TITLE
DB/Kube access IP Pinning

### ISSUE THREAD

**Issue by AntonAM** [gravitational/teleport#22061]
This is an umbrella ticket to track IP pinning for DB/Kube access goal: 

Success criteria:
- We have a secure way to pass client IP between services.
- Kubernetes Access supports IP pinning.
- Database Access supports IP pinning.

```[tasklist] 
### RFD 
- [x] https://github.com/gravitational/teleport/pull/22481
```

```[tasklist]
### Security fix
- [x] Fix SSH IP pinning bypass (https://github.com/gravitational/teleport/pull/19703)
```
```[tasklist]
### Implementation
- [x] https://github.com/gravitational/teleport/pull/18494
- [x] https://github.com/gravitational/teleport/pull/19008
- [x] https://github.com/gravitational/teleport/pull/21866
- [X] https://github.com/gravitational/teleport/pull/21080
- [X] https://github.com/gravitational/teleport/pull/22310
- [ ] https://github.com/gravitational/teleport/pull/23190
```
## Testing

Checks should be made with a user with IP pinning enbaled and a user without IP pinning.

For the sake of testing 12.2 is designated as the version where new IP propagation/pining system is enabled, servers lower than that version considered running old code, unaware of the introduced changes.

```[tasklist]
### Mini testplan for backporting and releasing at v12.2
- [x] **Test local cluster**
- [x]  - Connect to a SSH reverse tunnel node on remote cluster
- [x]  - Connect to a direct access node on a remote cluster
- [x]  - Connect to a database within a local cluster.
- [x]  - Connect to a local Kube service running in standalone mode
- [x]  - Connect to a local Kube service running inside kubernetes cluster
- [x] Verify that user with IP pinning enabled can't get SSH access from different IP
- [x] Verify that user with IP pinning enabled can't get DB access from different IP
- [x] Verify that user with IP pinning enabled can't get Kube access from different IP
- [x] Verify that tsh db connect works through proxy running in multiplex mode
- [x] **Test trusted clusters setup**
- [x]  - Connect to a SSH reverse tunnel node on remote cluster
- [x]  - Connect to a direct access node on a remote cluster
- [x]  - Connect to a Kube service on a remote cluster
- [x]  - Connect to a DB service on a remote cluster
- [x] Test upgrading of a cluster
- [x] Test upgrading of a trusted cluster
- [x] **Test connecting to a service with version >12.2 with proxy being <12.2**
- [x]  - For SSH direct access node
- [x]  - For SSH reverse tunnel node
- [x]  - For Kube access
- [x]  - For DB access
- [x] **Test connecting to a service with version <12.2 with proxy being >12.2**
- [x]  - For SSH direct access node
- [x]  - For SSH reverse tunnel node
- [x]  - For Kube access
- [x]  - For DB access
- [x] Test connection to a reverse tunnel node via web UI
- [x] Test connection to a direct access node via web UI
- [x] Test downloading/uploading files to a node via web UI
- [x] Verify that App Access still works correctly and is unaffected by the changes
- [x] Verify Desktop Access still works correctly and is unaffected by the changes
```

**Comment by strideynet** [comment]
Part of https://github.com/gravitational/teleport/issues/14702

**Comment by zmb3** [comment]
@AntonAM are we good to close this tracking issue now? Looks like all tasks have been completed.

**Comment by AntonAM** [comment]
@zmb3 Yes, closing.
