### ISSUE TITLE
RBAC Milestone Tracker

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#22526]
```[tasklist]
### Issues
- [x] https://github.com/gravitational/teleport/issues/20145
- [x] https://github.com/gravitational/teleport/issues/10204
- [x] https://github.com/gravitational/teleport/issues/10233
```

```[tasklist]
### Tasks
- [x] Investigate #16914 to see if it's already supported via `system_annotations` and document
- [x] https://github.com/gravitational/teleport/pull/24366
- [x] Implement label expressions https://github.com/gravitational/teleport/pull/27641
- [x] https://github.com/gravitational/teleport/pull/27811
- [x] Update Terraform + k8s operator with Role changes
```
