### ISSUE TITLE
BPF umbrella issue

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#22555]
Fix small papercuts for Enhanced Session Recording.

```[tasklist]
### 12.1.0
- [ ] https://github.com/gravitational/teleport/issues/19344
- [ ] https://github.com/gravitational/teleport/issues/14206
```

```[tasklist]
### 12.3.0
- [ ] https://github.com/gravitational/teleport/issues/16053
```

```[tasklist]
### 13.0.0
- [ ] https://github.com/gravitational/teleport/issues/22261
- [ ] https://github.com/gravitational/teleport.e/issues/937
- [ ] (Stretch) Advanced session recording works on lower kernel versions. TBD what versions to support.
```

**Comment by jakule** [comment]
I don't think anything here is important. Closing
