### ISSUE TITLE
Machine ID: Telemetry should capture presence of `CI` environment variable

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#22590]
This environment variable is often set to a truthy value when something is executed in CI - this may help us capture an idea that there are platforms we aren't supporting, but Machine ID is being used in.

```[tasklist]
### Tasks
- [ ] Add to PreHog
- [ ] Add to `tbot`
- [ ] Document existence on Telemetry reference page
```
