### ISSUE TITLE
Device Trust Milestone

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22808]
```[tasklist]
- [ ] Launch Microsoft Intune Integration
- [ ] Launch JamF Integration
- [ ] (Stretch) Build POC for TPM on Windows and Linux
```

**Comment by codingllama** [comment]
Hey @russjones, happy to keep this one as well, but we have another tracker at https://github.com/gravitational/teleport.e/issues/829.

**Comment by codingllama** [comment]
I'd also argue that Intune integration doesn't get us much far without TPM/Windows support. Most folks seems to run Jamf for macOS.

**Comment by russjones** [comment]
@codingllama Forgot to search teleport.e, will close this.
