### ISSUE TITLE
Stability Milestone

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#22807]
```[tasklist]
- [ ] Improve tsh ls -R performance on large clusters
- [ ] https://github.com/gravitational/teleport/issues/19885
- [ ] https://github.com/gravitational/teleport/issues/20057
- [ ] https://github.com/gravitational/teleport/issues/21586
- [ ] https://github.com/gravitational/teleport/pull/21190
```
