### ISSUE TITLE
SFTP papercuts

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#22933]
```[tasklist]
## P0
- [ ] https://github.com/gravitational/teleport/issues/22748
- [ ] https://github.com/gravitational/teleport/issues/21518
- [ ] https://github.com/gravitational/teleport/issues/23593
- [ ] https://github.com/gravitational/teleport/issues/22263
- [ ] https://github.com/gravitational/teleport/issues/20863
```

```[tasklist]
## P0.5
- [ ] https://github.com/gravitational/teleport/issues/22932
- [ ] https://github.com/gravitational/teleport/issues/23595
- [ ] https://github.com/gravitational/teleport/issues/22982
```

```[tasklist]
## P1
- [ ] https://github.com/gravitational/teleport/issues/22886
- [ ] https://github.com/gravitational/teleport/issues/22710
- [ ] https://github.com/gravitational/teleport/issues/20720
- [ ] (missing docs) https://github.com/gravitational/teleport/issues/20619
- [ ] https://github.com/gravitational/teleport/issues/20116
- [ ] https://github.com/gravitational/teleport/issues/18098
- [ ] https://github.com/gravitational/teleport/issues/11021
- [ ] https://github.com/gravitational/teleport/issues/10714
- [ ] https://github.com/gravitational/teleport/issues/3900
- [ ] https://github.com/gravitational/teleport/issues/23919
- [ ] https://github.com/gravitational/teleport/issues/15621
```

**Comment by zmb3** [comment]
@jakule @capnspacehook please add #23593 to this list

**Comment by jakule** [comment]
@rosstimothy Let me figure this out and I'll come back to you.
