### ISSUE TITLE
Epic: Overhaul HA Terraform example to bring it up to date with Helm charts

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#24785]
Tracking issue for updating the woefully outdated [HA Terraform example](https://github.com/gravitational/teleport/tree/master/examples/aws/terraform/ha-autoscale-cluster) to have some kind of feature parity with the `teleport-cluster` Helm chart.

### Modularisation
- [ ] https://github.com/gravitational/teleport/issues/16553

### Monitoring stack
- [ ] https://github.com/gravitational/teleport/issues/2734
- [ ] https://github.com/gravitational/teleport/issues/4756
- [ ] https://github.com/gravitational/teleport/issues/4572

### Compatibility/bugs/missing features
- [ ] https://github.com/gravitational/teleport/issues/23788
- [ ] https://github.com/gravitational/teleport/issues/22214
- [ ] https://github.com/gravitational/teleport/issues/12404
- [ ] https://github.com/gravitational/teleport/issues/8467
- [ ] https://github.com/gravitational/teleport/issues/6375
- [ ] https://github.com/gravitational/teleport/issues/5377
- [ ] https://github.com/gravitational/teleport/issues/4803
- [ ] https://github.com/gravitational/teleport/issues/4774
- [ ] https://github.com/gravitational/teleport/issues/4739
- [ ] https://github.com/gravitational/teleport/issues/10992
- [ ] https://github.com/gravitational/teleport/issues/8900

### Multiplexing/LBs
- [ ] https://github.com/gravitational/teleport/issues/16684
- [ ] https://github.com/gravitational/teleport/issues/23570
- [ ] https://github.com/gravitational/teleport/issues/16682

### Documentation
- [ ] https://github.com/gravitational/teleport/issues/17840
- [ ] https://github.com/gravitational/teleport/issues/17733
- [ ] https://github.com/gravitational/teleport/issues/11284

### Overall architecture changes
- [ ] https://github.com/gravitational/teleport/issues/19964
- [ ] https://github.com/gravitational/teleport/issues/12613
