### ISSUE TITLE
Add ability to manage auto-discovery settings dynamically

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#25494]
We will be adding auto-discovery support to our Teleport Discover resource adding UI, starting with RDS.

To support it, we need ability to manage auto-discovery settings (e.g. update cloud resource filters) dynamically.
Right now it's just a static configuration with `discovery_service` config file.

The approach we discussed with @marcoandredinis is to create a new resource e.g. `DiscoveryConfig` that supports same filters as `discovery_service`:

```yaml
kind: DiscoveryConfig
version: v1
metadata:
  name: production-resources
spec:
  discovery_group: prod
  // AWS auto-discovery matchers
  aws:
    ...
  // Azure auto-discovery matchers
  azure:
    ...
  // GCP auto-discovery matchers
  gcp:
    ...
  // Kube auto-discovery matchers
  kube:
    ...
```

`discovery_service`
```yaml
discovery_service:
  enabled: "yes"
  discovery_group: prod
```

A `discovery_service` will monitor DiscoveryConfig resources and will dynamically update its auto-discovery configuration based on the resources that match its `discovery_group` field.

A DiscoveryService must be running with a well known `discovery_group` (eg "default").
For Cloud customers, this will be automatic (managed by Teleport Cloud).

When enrolling an RDS database, during the `Deploy Database Service` step, users should be able to enable auto-discovery for the current resource type/region and a set of labels.
This will create the following DiscoveryConfig:
```yaml
kind: DiscoveryConfig
metadata:
  name: <uuid>
spec:
  discovery_group: default
  aws:
  - types: ["rds"]
    region: ["<db-region>"]
    labels: ...
    integration: "<integration>"
```

The DiscoveryService will receive this new matcher and will monitor those resources.
However, instead of using the credentials provider chain, it will use the integration to authenticate in AWS APIs.

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/26613
- [ ] https://github.com/gravitational/teleport/pull/27162
- [ ] https://github.com/gravitational/teleport/pull/32325
- [ ] https://github.com/gravitational/teleport/pull/32035
- [ ] https://github.com/gravitational/teleport/pull/32328
- [ ] https://github.com/gravitational/teleport/pull/32371
- [ ] https://github.com/gravitational/teleport/pull/32857
- [ ] https://github.com/gravitational/teleport/pull/32399
- [ ] https://github.com/gravitational/teleport/pull/32591
- [ ] https://github.com/gravitational/teleport/pull/33472
- [ ] https://github.com/gravitational/teleport/pull/34221
- [ ] https://github.com/gravitational/teleport/pull/34530
- [ ] https://github.com/gravitational/teleport/pull/34582
- [ ] https://github.com/gravitational/cloud/pull/6317
- [ ] https://github.com/gravitational/teleport/pull/35899
- [ ] https://github.com/gravitational/teleport/pull/35820
- [ ] https://github.com/gravitational/teleport/pull/35719
- [ ] https://github.com/gravitational/teleport/pull/35775
- [ ] https://github.com/gravitational/teleport/pull/35793
- [ ] https://github.com/gravitational/teleport/pull/35972
- [ ] https://github.com/gravitational/teleport/pull/36561
- [ ] https://github.com/gravitational/teleport/pull/36558
- [ ] https://github.com/gravitational/teleport/pull/36570
- [ ] https://github.com/gravitational/teleport/pull/38204
- [ ] https://github.com/gravitational/teleport/pull/40937
- [ ] https://github.com/gravitational/teleport/pull/40959
- [ ] https://github.com/gravitational/cloud/issues/6795
- [ ] https://github.com/gravitational/teleport/pull/35504
```
