### ISSUE TITLE
ClickHouse Database Access integration with HTTP/Native Wire Protocols support

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#26219]
This is an umbrella ticket to track Clickhouse integration: 

### ClickHouse HTTP Protocol (13.1- 13.2)

```[tasklist]
- [x] ClickHouse HTTP protocol Database Access
- [x] ClickHouse Audit Events support for HTTP protocol
- [x] Documentation
```

### ClickHouse Native Wire Protocol Database  Access integration (13.2 - 14.0)

```[tasklist]
- [x] ClickHouse Native Wire protocol support
- [ ] Audit logs for Native Wire protocol
- [x] Documentation
```
##### Success criteria:
- Teleport supports Clickhouse in database access.

Related Items: 
https://github.com/gravitational/teleport/issues/12149

**Comment by zmb3** [comment]
@smallinsky good to close this one or do we still need it for tracking?

**Comment by smallinsky** [comment]
We still don't have support for "Audit logs for Native Wire protocol" but we can handle this as a separate issue.
