### ISSUE TITLE
Azure Support as Teleport Backend Reactivation 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#26216]
This is an umbrella ticket to track Azure support as Teleport Backend: 

### Azure Teleport Backend Support (13.x-14.0)

```[tasklist]
- [x] Revive the Postgres cluster and audit event backend from https://github.com/gravitational/teleport/tree/espadolini/pgbk2
- [x] Revive the Azure Blob Storage implementation from https://github.com/gravitational/teleport/pull/16144
- [x] Run through the [Performance](https://github.com/gravitational/teleport/blob/master/.github/ISSUE_TEMPLATE/testplan.md#performance) section of the test plan with the new backend
- [x] Push the events backend by generating a large number of events at once (`tctl create` several fake nodes, tsh bench)
- [x] Test and validate that session storage is functional and that recordings can be replayed
- [ ] Terraform/ Helm Charts/ Dependency alignment
- [ ] Documentation Update
```

##### Success criteria:
- Teleport supports Postgres for cluster state and audit log.
- Teleport supports Azure Blob Storage for session recordings.

Related Items: 
https://github.com/gravitational/teleport/issues/15147
https://github.com/gravitational/teleport/issues/5956
https://github.com/gravitational/teleport/pull/16144
https://github.com/gravitational/teleport/issues/22072

**Comment by andreiko** [comment]
Some load test results from today.

## Soak (with 1000 tunnel agents)

### Random (unsuccessful)

Start time: 1:06PM

root@bench-86557c7999-hr4r7:/# tsh bench ssh --duration=30m --random root@all uptime

* Requests originated: 18000
* Requests failed: 7879
* Last error: failed connecting to host ec4d0c85-926f-4c6c-b914-21428dd654f0:0: failed to dial target host
	unable to locate node matching UUID-like target ec4d0c85-926f-4c6c-b914-21428dd654f0

Histogram

Percentile Response Duration
---------- -----------------
25         63 ms
50         150 ms
75         163 ms
90         178 ms
95         195 ms
99         232 ms
100        1268 ms

**Notes:**
Node with UUID ec4d0c85-926f-4c6c-b914-21428dd654f0 didn't exist at the end of the test.

<img width="857" alt="Screenshot 2023-06-15 at 11 44 20 PM" src="https://github.com/gravitational/teleport/assets/340586/57d827f9-3a56-424e-9465-3a5cf9846091">

### Specific tunnel node

Time: 1:42PM

root@bench-86557c7999-hr4r7:/# tsh bench ssh --duration=30m root@node-agents-5dd66bdfb7-n55vt-09 uptime

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration
---------- -----------------
25         151 ms
50         156 ms
75         162 ms
90         167 ms
95         171 ms
99         208 ms
100        432 ms


### By label

Time: 2:16PM

root@bench-86557c7999-hr4r7:/# tsh bench ssh --duration=30m root@fullname=node-agents-5dd66bdfb7-wn9k9-16 uptime

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration
---------- -----------------
25         193 ms
50         205 ms
75         212 ms
90         216 ms
95         224 ms
99         254 ms
100        307 ms

### Random again

Time: 2:47PM

root@bench-86557c7999-hr4r7:/# tsh bench ssh --duration=30m --random root@all uptime

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration
---------- -----------------
25         153 ms
50         159 ms
75         167 ms
90         177 ms
95         192 ms
99         229 ms
100        1221 ms

### Specific direct node

Time: 3:35PM

root@bench-86557c7999-hr4r7:/# tsh bench ssh --duration=30m root@direct-node-agents-ccfcdf6b7-lkqkn-08 uptime

* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration
---------- -----------------
25         146 ms
50         152 ms
75         157 ms
90         160 ms
95         164 ms
99         211 ms
100        374 ms

## Sessions

### Concurrent sessions (unsuccessful)

Time: 4:23PM

root@bench-86557c7999-hr4r7:/# tsh bench web sessions --mfa-mode=otp --max=5000 root uptime
Enter password for Teleport user test:
Enter an OTP code from a device:

[x26]
WARN             Unable to send error to terminal: read tcp 192.168.64.45:58538->44.237.215.209:443: read: connection reset by peer error:[
ERROR REPORT:
Original Error: *tls.permanentError write tcp 192.168.64.45:58538-&gt;44.237.215.209:443: write: broken pipe
Stack Trace:
        github.com/gravitational/teleport/lib/web/terminal.go:1259 github.com/gravitational/teleport/lib/web.(*WSStream).Write
        strings/replace.go:319 strings.stringWriter.WriteString
        strings/replace.go:371 strings.(*genericReplacer).WriteString
        strings/replace.go:103 strings.(*Replacer).WriteString
        github.com/gravitational/teleport/lib/web/terminal.go:989 github.com/gravitational/teleport/lib/web.(*WSStream).writeError
        github.com/gravitational/teleport/lib/web/terminal.go:1019 github.com/gravitational/teleport/lib/web.(*WSStream).processMessages
        runtime/asm_arm64.s:1172 runtime.goexit
User Message: write tcp 192.168.64.45:58538-&gt;44.237.215.209:443: write: broken pipe] web/terminal.go:990

* Requests originated: 8826
* Requests failed: 8825
* Last error: websocket: bad handshake

Histogram

Percentile Response Duration
---------- -----------------
25         24 ms
50         26 ms
75         29 ms
90         33 ms
95         36 ms
99         62 ms
100        63807 ms

<img width="853" alt="Screenshot 2023-06-15 at 11 40 29 PM" src="https://github.com/gravitational/teleport/assets/340586/15b4a638-f39d-4f81-9dfa-af965a788d53">


### Concurrent sessions again (unsuccessful)

Time: 8:08PM

root@bench-86557c7999-hr4r7:/# tsh bench web sessions --mfa-mode=otp --max=5000 root uptime
Enter password for Teleport user test:
Enter an OTP code from a device:

WARN             Unable to send error to terminal: read tcp 192.168.64.45:48470->34.212.5.244:443: read: connection reset by peer error:[
ERROR REPORT:
Original Error: *tls.permanentError write tcp 192.168.64.45:48470-&gt;34.212.5.244:443: write: broken pipe
Stack Trace:
        github.com/gravitational/teleport/lib/web/terminal.go:1259 github.com/gravitational/teleport/lib/web.(*WSStream).Write
        strings/replace.go:319 strings.stringWriter.WriteString
        strings/replace.go:371 strings.(*genericReplacer).WriteString
        strings/replace.go:103 strings.(*Replacer).WriteString
        github.com/gravitational/teleport/lib/web/terminal.go:989 github.com/gravitational/teleport/lib/web.(*WSStream).writeError
        github.com/gravitational/teleport/lib/web/terminal.go:1019 github.com/gravitational/teleport/lib/web.(*WSStream).processMessages
        runtime/asm_arm64.s:1172 runtime.goexit
User Message: write tcp 192.168.64.45:48470-&gt;34.212.5.244:443: write: broken pipe] web/terminal.go:990

* Requests originated: 8847
* Requests failed: 8816
* Last error: websocket: bad handshake

Histogram

Percentile Response Duration
---------- -----------------
25         24 ms
50         26 ms
75         29 ms
90         33 ms
95         37 ms
99         57 ms
100        50463 ms

#### proxy logs
```
[x 1474 ]
{"caller":"web/terminal.go:742","component":"websocket","error":"wait: remote command exited without exit status or exit signal","level":"warning","message":"Unable to stream terminal - failure running interactive shell","session_id":"988d31b5-c154-4b1b-bb18-54ce27990fed","timestamp":"2023-06-16T05:34:05Z"}
{"caller":"web/terminal.go:990","component":"websocket","error":"write tcp 192.168.91.40:3080-\u003e192.168.75.239:42359: write: broken pipe","level":"warning","message":"Unable to send error to terminal: wait: remote command exited without exit status or exit signal","session_id":"988d31b5-c154-4b1b-bb18-54ce27990fed","timestamp":"2023-06-16T05:34:05Z"}
```
#### auth logs
```
[x 12]
{"attempt":1,"caller":"pgbk/pgbk.go:125","component":"pgbk","error":null,"level":"debug","message":"Operation failed, retrying.","timestamp":"2023-06-16T04:40:54Z"}
```

<img width="858" alt="Screenshot 2023-06-15 at 11 42 45 PM" src="https://github.com/gravitational/teleport/assets/340586/775bc4a9-67e9-45f3-9968-5ced24a25770">

**Comment by andreiko** [comment]
## Scaling tests

### 0 - 10k tunnel nodes

<img width="856" alt="Screenshot 2023-06-16 at 11 13 23 PM" src="https://github.com/gravitational/teleport/assets/340586/2f823c2f-1be4-4c87-b3ee-3efb85bda63b">

### 0 - 10k direct nodes

<img width="855" alt="Screenshot 2023-06-16 at 11 14 53 PM" src="https://github.com/gravitational/teleport/assets/340586/76143ec3-4c60-49de-b07e-c5b3038710a3">

### 0 - 500 connected clusters

<img width="856" alt="Screenshot 2023-06-16 at 11 17 05 PM" src="https://github.com/gravitational/teleport/assets/340586/82ecc207-3b76-424e-8880-352cca45b123">

**Comment by andreiko** [comment]
Ran the random soak test again for good measure because it failed once yesterday.

```
root@bench-86557c7999-f7fnq:/# tsh bench ssh --duration=30m --random root@all uptime

* Requests originated: 17990
* Requests failed: 0

Histogram

Percentile Response Duration
---------- -----------------
25         1031 ms
50         1048 ms
75         1065 ms
90         1087 ms
95         1114 ms
99         3497 ms
100        8471 ms
```

<img width="853" alt="Screenshot 2023-06-16 at 11 21 09 PM" src="https://github.com/gravitational/teleport/assets/340586/f0e20b1c-630a-43f0-884c-51d446878c77">

**Comment by espadolini** [comment]
10k tunnel nodes: joining, auth rollout restart, spin down, spin up, spin down
<img width="1705" alt="10k_tunnel_backend" src="https://github.com/gravitational/teleport/assets/886075/6a261634-c0ad-4909-9d7d-b9670a8435c8">
<img width="854" alt="10k_tunnel_connections" src="https://github.com/gravitational/teleport/assets/886075/05152af5-647e-4544-888b-818cf314a82c">
<img width="1706" alt="10k_tunnel_instance" src="https://github.com/gravitational/teleport/assets/886075/a363ae0e-f108-4b9f-bed4-e5d18c76a64b">

AKS cluster on 12 `Standard_D16s_v3` nodes, Postgres on `Standard_D2ds_v5` in SameZone HA (because West Europe has a single AZ, apparently)

**Comment by espadolini** [comment]
1k tunnel nodes, label-based ssh
```
# tsh bench ssh --duration 30m root@fullname=node-agent-744b56ccf4-g62db-12 uptime
* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         179 ms            
50         184 ms            
75         191 ms            
90         199 ms            
95         205 ms            
99         220 ms            
100        438 ms            
```

1k tunnel nodes, all random ssh
```
# tsh bench ssh --duration 30m --random root@all uptime
* Requests originated: 17999
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         158 ms            
50         167 ms            
75         218 ms            
90         250 ms            
95         282 ms            
99         307 ms            
100        2249 ms  
```

1k tunnel nodes, 5000 concurrent web sessions
```
# tsh bench web sessions --max=5000 root uptime                                                                                                                          
Enter password for Teleport user joe:

* Requests originated: 600
* Requests failed: 0

Histogram

Percentile Response Duration 
---------- ----------------- 
25         0 ms              
50         0 ms              
75         0 ms              
90         1 ms              
95         2 ms              
99         5 ms              
100        13 ms             
```
<img width="1707" alt="1k_tunnel_concurrent_5k_backend" src="https://github.com/gravitational/teleport/assets/886075/c68a9625-7027-4e46-90da-d56a078853fb">
<img width="1708" alt="1k_tunnel_concurrent_5k_instance" src="https://github.com/gravitational/teleport/assets/886075/1b9e0489-5b42-4ce0-aab5-a2a5b5d37045">

**Comment by anthonysomerset** [comment]
heads up i am seeing this bug in logs repeatedly in logs:

I might have done something wrong or have an actual config issue - will open a separate issue

```
2023-08-02T15:01:33Z INFO [PGBK]      Change feed started. slot_name:da158aeccba74b6591580526fc587072 pgbk/background.go:170
2023-08-02T15:01:39Z WARN [AUTH:1:CA] Re-init the cache on error error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError watcher is closed: &lt;nil&gt;
Stack Trace:
	github.com/gravitational/teleport/lib/cache/cache.go:1158 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	github.com/gravitational/teleport/lib/cache/cache.go:956 github.com/gravitational/teleport/lib/cache.(*Cache).update
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: watcher is closed: &lt;nil&gt;] cache/cache.go:962
2023-08-02T15:01:39Z ERRO [PGBK]      Change feed stream lost. error:[
ERROR REPORT:
Original Error: *pgconn.PgError ERROR: invalid hexadecimal digit: &#34;-&#34; (SQLSTATE 22023)
Stack Trace:
	github.com/gravitational/teleport/lib/backend/pgbk/background.go:263 github.com/gravitational/teleport/lib/backend/pgbk.(*Backend).pollChangeFeed
	github.com/gravitational/teleport/lib/backend/pgbk/background.go:175 github.com/gravitational/teleport/lib/backend/pgbk.(*Backend).runChangeFeed
	github.com/gravitational/teleport/lib/backend/pgbk/background.go:101 github.com/gravitational/teleport/lib/backend/pgbk.(*Backend).backgroundChangeFeed
	github.com/gravitational/teleport/lib/backend/pgbk/pgbk.go:206 github.com/gravitational/teleport/lib/backend/pgbk.NewWithConfig.func2
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: ERROR: invalid hexadecimal digit: &#34;-&#34; (SQLSTATE 22023)] pgbk/background.go:105
2023-08-02T15:01:39Z WARN [PROC:1]    Sync rotation state cycle failed. Retrying in ~10s pid:8.1 service/connect.go:826
2023-08-02T15:01:39Z WARN [KUBERNETE] Re-init the cache on error error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError watcher is closed: rpc error: code = Unknown desc = watcher closed
Stack Trace:
	github.com/gravitational/teleport/lib/cache/cache.go:1158 github.com/gravitational/teleport/lib/cache.(*Cache).fetchAndWatch
	github.com/gravitational/teleport/lib/cache/cache.go:956 github.com/gravitational/teleport/lib/cache.(*Cache).update
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: watcher is closed: rpc error: code = Unknown desc = watcher closed] cache/cache.go:962
2023-08-02T15:01:39Z WARN             Restarting watch on error after waiting 389.200812ms. Error: watcher closed. local/headlessauthn_watcher.go:156
2023-08-02T15:01:40Z WARN [AUTH:1]    Restart watch on error: watcher is closed: <nil>. pid:8.1 resource-kind:lock services/watcher.go:246
2023-08-02T15:01:44Z WARN [KUBERNETE] Restart watch on error: watcher is closed: rpc error: code = Unknown desc = watcher closed. pid:8.1 resource-kind:lock services/watcher.go:246
2023-08-02T15:01:49Z INFO [PGBK]      Starting change feed stream. pgbk/background.go:100
2023-08-02T15:01:49Z INFO [PGBK]      Setting up change feed. slot_name:46d6e54ad7aa4e4f8d8f99e530df1b4e pgbk/background.go:162
```

**Comment by espadolini** [comment]
Issue tracked in https://github.com/gravitational/teleport/issues/29911

**Comment by zmb3** [comment]
This has been released.
