### ISSUE TITLE
Database Access: Stability/Performance/Observability

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#26224]
This is an umbrella ticket to track Stability/Performance/Observability improvements: 

### Database Access Observability

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/26667
- [ ] https://github.com/gravitational/teleport/issues/26668
- [ ] https://github.com/gravitational/teleport/issues/26669
- [ ] https://github.com/gravitational/teleport/issues/28743
```

###  Database Access Performance

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/27533
- [ ] https://github.com/gravitational/teleport/issues/27534
- [ ] https://github.com/gravitational/teleport/issues/27838
- [x] Database Bench Grafana Dashboards.
- [ ] tsh bench db for MongoDB
- [ ] tsh bench db for other protocols.
- [ ] https://github.com/gravitational/teleport/issues/26868
- [x] Comparing Teleport Database Access Overhead vs Direct DB Access
- [ ] https://github.com/gravitational/teleport/issues/28993
```

###  Database Access Stability

```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/21158
- [x] Teleport E2E Infrastructure
- [ ] https://github.com/gravitational/teleport/issues/27325
- [x] Regression test suite for MySQL/Postgres RDS Databases.
- [ ] Teleport Cloud integration.
- [ ] CI nightly build integration
```

### Other: 
```[tasklist]
- [ ] https://github.com/gravitational/teleport/issues/22717
```

**Comment by GavinFrazar** [comment]
@smallinsky under the "Database Access Stability" section, do the items `Teleport E2E Infrastructure`, `Regression test suite for MySQL/Postgres RDS Databases`, and `CI nightly build integration` all fall under `Database Access E2E tests`? Or if they don't, what needs to be done specifically?

The AWS e2e tests I added:
1. deploy test infra to AWS in cloud-terraform repo
2. added tests for mysql/postgres RDS
3. are enabled in CI for each PR (not nightly though)

Just want to clarify if these other items are redundant or actually require more work.

**Comment by smallinsky** [comment]
> @smallinsky under the "Database Access Stability" section, do the items Teleport E2E Infrastructure, Regression test suite for MySQL/Postgres RDS Databases, and CI nightly build integration all fall under Database Access E2E tests? Or if they don't, what needs to be done specifically?

> The AWS e2e tests I added:

> deploy test infra to AWS in cloud-terraform repo
added tests for mysql/postgres RDS
are enabled in CI for each PR (not nightly though)
Just want to clarify if these other items are redundant or actually require more work.

Agree. All "Database Access Stability" points all covered by your e2e changes where "Teleport Cloud integration: seem to be not longer valid. 

I think that we should consider adding more test coverage for `tsh db connect` `tsh db proxy` flow in integration tests but we can track it as a separate item.

**Comment by zmb3** [comment]
@smallinsky are you still using this issue for tracking or can we close it? Doesn't seem like it's been updated recently.

**Comment by smallinsky** [comment]
> @smallinsky are you still using this issue for tracking or can we close it? Doesn't seem like it's been updated recently.

no, I'm closing this one since.
