### ISSUE TITLE
Connect My Computer

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#27881]
[RFD 133](https://github.com/gravitational/teleport/blob/master/rfd/0133-connect-my-computer.md)

```[tasklist]
### Setup
- [x] Foundation (WIP CTA + new document) #28063
- [x] Checking permissions before showing CMC in the UI + feature flag #28346
- [x] Setting up the roles (#28891 & #28956)
- [ ] https://github.com/gravitational/teleport/issues/28181
- [x] Generating the config file https://github.com/gravitational/teleport/pull/29010
- [x] Joining the cluster https://github.com/gravitational/teleport/pull/29479
- [ ] https://github.com/gravitational/teleport/issues/28281
- [ ] #32312
```

<details>
<summary>Setup implementation details</summary>

Once we agree on the UI, it's likely we'll have to go back to the setup steps and adjust them a little bit. For example, launching the agent during the setup might initially be much simpler than what we'll need later on to get updates on the status of the agent process. However, initially we shouldn't concern ourselves with that, we want to just implement the setup, let's just keep in mind that we're probably have to share some state between the setup doc and the rest of the UI.

The renderer is going to perform all four steps. Some of them will need access to tshd client (such as setting up the roles), while others will need to talk with the main process (such as downloading the agent). Since we need to report the status of each step to the user, it'll be easier to just have some kind of a separate handler for each step.

When checking permissions, always check them for the root cluster - ACL is not defined for leafs.  

#### Joining the cluster

For now just start the agent without checking if the node successfully joined the cluster. 
</details>

```[tasklist]
### Status UI
- [ ] https://github.com/gravitational/teleport/issues/28934
```

```[tasklist]
### Agent lifecycle
- [ ] #30905
- [ ] #30758
- [ ] #31020
- [ ] #31951
- [x] https://github.com/gravitational/teleport/pull/31638
```

```[tasklist]
### Other
- [x] Telemetry https://github.com/gravitational/cloud/pull/5552 https://github.com/gravitational/teleport/pull/30033
- [ ] #29896
- [ ] #32798
```

### Important

- [x] Either bring back old `GenerateUserCerts` behavior (#31068) or ask for relogin during setup.
- [x] Single ConnectMyComputer doc rather than two separate document types for status and setup (https://github.com/gravitational/teleport/pull/31699)
   - Still, the distinction between setup and status is important on subcomponent level.
   - This would also fix the problem with setup redirect described below.
- [x] Logs are not stored to disk (https://github.com/gravitational/teleport/pull/32044).
   - Create a LoggerService for each agent on spawn event.
- [x] Move the icon to top left (https://github.com/gravitational/teleport/pull/31751).
   - Use a portal for this, see `ravicious/cmc-portal-example`.
- [x] The default CTA on the status page when the agent is running should be Start SSH Session, not Disconnect (https://github.com/gravitational/teleport/pull/31794)
- [x] Make the logs on the status page wider (https://github.com/gravitational/teleport/pull/31794)
- [x] The icon should be visible when the user has permissions to set up Connect My Computer _or_ if the agent has been already set up (https://github.com/gravitational/teleport/pull/31794)
- [x] Do not omit checking all permissions when the agent is configured (https://github.com/gravitational/teleport/pull/31927)

### Good to have

- ~Setup should redirect to Status (as in open the tab) only if Setup is the current active location.~
- Rather minor issue: `CreateConnectMyComputerRole` should return not `certsReloaded`, but the name of the created role.
   - The UI should then check if the created role is in the list of roles of the current user. If not, it should sync root cluster details.
   - With the current implementation, in a pristine state if `CreateConnectMyComputerRole` succeeds but the attepm to `GetCluster` fails and you attempt to repeat the setup, `CreateConnectMyComputerRole` will return `certsReloaded: false` and the app won't attempt to refresh the certs in the UI.
- Attempt to call `RemoveNode` after stopping the agent. Otherwise the agent will linger in the cache.
   - This means that the agents need to be stopped before tshd.

## Stretch

- Use a single role with traits. https://github.com/gravitational/teleport/pull/28891#discussion_r1263028889
- Add animations for error boxes in Setup
- Show download progress in the UI (electron native progress bar does not work on Linux)
- `teleport` CLI API tests (detecting breaking changes)

## After release

- Discover tile with link to docs

**Comment by ravicious** [comment]
Moved docs & the Discover tile to the new "After release" section. The release of the feature will mean that Connect My Computer is available in Connect. After the release we'll work on getting people to use it.

Removed WSL from the stretch goals. We'll think of WSL if the feature gains traction.

Moved `teleport` CLI API tests to the stretch goals. The API is unlikely to change, so the tests would not bring as much value.
