### ISSUE TITLE
Modern signature algorithms tracker

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#28392]
## RFD

```[tasklist]
- [ ] https://github.com/gravitational/teleport/pull/28110
```

## Configurable user key types (14.0)

```[tasklist]
- [ ] split user SSH and TLS keys
- [ ] configurable algorithms for user SSH and TLS keys
- [ ] configurable algorithms for user JWTs
- [ ] configurable algorithms for database certs
- [ ] documentation
- [ ] terraform support
- [ ] helm chart support
- [ ] operator support
- [ ] use modern algorithms by default
```

## Configurable CA key types and signature algorithms (TBD)

```[tasklist]
- [ ] software keystore support for new algorithms
- [ ] GCP KMS keystore support for new algorithms
- [ ] PKCS#11 keystore support for new algorithms
- [ ] static configuration of CA key algorithms via `teleport.yaml`
- [ ] dynamic configuration of CA key algorithms via `cluster_auth_preference`
- [ ] documentation
- [ ] terraform support
- [ ] helm chart support
- [ ] operator support
- [ ] use modern algorithms by default (maybe not 14.0)
```

## Update host key types (TBD)

```[tasklist]
- [ ] split host TLS and SSH keys
- [ ] update algorithms for host TLS and SSH keys
```

## Related Issues

- https://github.com/gravitational/teleport/issues/3489
- https://github.com/gravitational/teleport/issues/22505

**Comment by benarent** [comment]
@nklaassen , Do we have any update on docs for this feature?

**Comment by nklaassen** [comment]
Hey @benarent the docs PR is up https://github.com/gravitational/teleport/pull/47976
