### ISSUE TITLE
SSH into any EC2 using EC2 Instance Connect Endpoint

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#29317]
AWS released a new tool to connect to EC2 instances.
This allows ssh access even if they only have private subnets.
https://aws.amazon.com/blogs/compute/secure-connectivity-from-public-to-private-introducing-ec2-instance-connect-endpoint-june-13-2023/

Teleport must be able to use this feature to allow SSH access to any EC2 instance.
This will greatly reduce the number of steps required to access the nodes.

A high level flow will look something like this:
- using the Discover Wizard, the user selects EC2 resource
- the user either picks an AWS OIDC Integration or creates a new one
- the user receives a list of EC2 Instance and picks one (similar to RDS flow) and adds it
- the node is now available as a regular SSH Node

Technically it should work like this:
- a new endpoint to list EC2 instances as Nodes that adds some AWS Meta Information required for connecting
- a new endpoint that will save Nodes with the AWS Meta Information
- when a user tries to connect, the proxy will:
  - create a new tcp listener (a) locally and forward any connections to the endpoint of the EC2's vpc using websockets
  - create and upload an SSH Key to the target EC2 instance
  - receive the ssh connection from clients (web terminal, `tsh ssh`), create a new ssh connection to (a) with the SSH Key created above

This mode is very similar to Agentless Nodes access in terms of Teleport features (session recording, RBAC, moderated sessions, ...).

EC2 Instance Connect Endpoint 

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/29316
- [ ] https://github.com/gravitational/teleport/pull/29366
- [ ] https://github.com/gravitational/teleport/pull/29370
- [ ] https://github.com/gravitational/teleport/pull/30699
- [ ] https://github.com/gravitational/teleport/pull/30692
- [ ] https://github.com/gravitational/teleport/pull/30851
- [ ] https://github.com/gravitational/teleport/pull/30915
- [ ] https://github.com/gravitational/teleport/pull/30632
- [ ] https://github.com/gravitational/cloud/pull/5769
- [ ] https://github.com/gravitational/teleport/pull/30774
- [ ] https://github.com/gravitational/teleport/pull/30866
- [ ] https://github.com/gravitational/teleport/pull/31139
- [ ] https://github.com/gravitational/teleport/pull/31209
- [ ] https://github.com/gravitational/teleport/pull/31415
- [ ] https://github.com/gravitational/teleport/pull/31498
- [ ] https://github.com/gravitational/teleport/pull/31179
- [ ] https://github.com/gravitational/teleport/pull/32202
- [ ] https://github.com/gravitational/teleport/pull/32899
```

**Comment by marcoandredinis** [comment]
This is now completed and released in v14 and v13

**Comment by diogonicoleti** [comment]
Hi @marcoandredinis the SSH into an EC2 instance using Instance Connect is a awesome feature!

I don't know if it's the best place to ask but I would like to know if I can already use the EC2 Instance Connect Endpoint with EC2 Instance Discovery?

**Comment by marcoandredinis** [comment]
Hi @diogonicoleti 
Not yet, sorry.

Feel free to create an issue so that we can track that request.

I was wondering if we could add another method to the AWS EC2, given that we already support 2 modes already: teleport installation and openssh ca configuration.
We would also need a way to set the security groups for this method.
Would that be how you imagine the configuration for this access mode?

**Comment by diogonicoleti** [comment]
created @marcoandredinis: https://github.com/gravitational/teleport/issues/34291
