### ISSUE TITLE
Teleport Kubernetes operator improvements epic

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#29480]
Allow the operator to be deployed by itself:
- [x] https://github.com/gravitational/teleport/issues/15014

Resources/improvements:
- [ ] https://github.com/gravitational/teleport/issues/20970
- [ ] https://github.com/gravitational/teleport/issues/20971
- [ ] https://github.com/gravitational/teleport/issues/22474
- [ ] https://github.com/gravitational/teleport/issues/26756
- [x] https://github.com/gravitational/teleport/issues/29438
- [x] https://github.com/gravitational/teleport/issues/27938
- [ ] https://github.com/gravitational/teleport/issues/22476
- [ ] https://github.com/gravitational/teleport/issues/21419
- [ ] https://github.com/gravitational/teleport/issues/21416

Bugs:
- [x] https://github.com/gravitational/teleport/issues/24110
- [ ] https://github.com/gravitational/teleport/issues/23382
- [ ] https://github.com/gravitational/teleport/issues/22557
- [x] https://github.com/gravitational/teleport/issues/21826 
- [x] https://github.com/gravitational/teleport/issues/29686
- [x] https://github.com/gravitational/teleport/issues/34092
- [x] https://github.com/gravitational/teleport/issues/34423

Docs:
- [x] https://github.com/gravitational/teleport/issues/23097

Tests:
- [x] https://github.com/gravitational/teleport/issues/29006

**Comment by tigrato** [comment]
#20398 aims to fix #27938 without relying on `webhooks`.

The code needs to be tested.

**Comment by tigrato** [comment]
Edited to include https://github.com/gravitational/teleport/issues/29686

**Comment by dmitry-mightydevops** [comment]
Would like to include this: https://github.com/gravitational/teleport/issues/32995

**Comment by bsgrigorov** [comment]
Can we add these as well:
- fix reconciliation of v6 roles (currently causes operator to spam millions of upsert logs and crash the auth pod)
- add support for v7 roles
- add support for teleport bot custom resources
- split off operator in a separate pod from the auth proxy so that if the operator crashes it does not crash the auth proxy

**Comment by tigrato** [comment]
> * fix reconciliation of v6 roles (currently causes operator to spam millions of upsert logs and crash the auth pod)
> 
> * add support for v7 roles
> 
> * add support for teleport bot custom resources

hello @bsgrigorov ,

All the issues you mention are already included in this EPIC.

We will work on it this quarter by the following order:
- standalone deployment - **critical for us**
- operator bot self-lock  - _the previous point should fix it._
- huge memory/cpu consumption from the operator 
- support v6/v7 roles
- all the other minor issues

Thanks,
Tiago

**Comment by zmb3** [comment]
Closing this as it hasn't seen updates in 6 months. This does not mean that we won't work on the remaining issues, only that we won't be using this tracking issue any longer.
