### ISSUE TITLE
Audit security reports

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#29647]
```[tasklist]
### Feature request
- [ ] https://github.com/gravitational/teleport.e/issues/1597
```

```[tasklist]
### MVP phase (Aug '23)
- [ ] Build prototype security reports backend that provides API and CLI for defining and running audit queries @smallinsky
- [ ] Research building SQL queries in Assist @hugoShaka
- [ ] Build prototype security reports UI for web UI and Assist @ryanclark
```
