### ISSUE TITLE
[Tracking] Update READMEs for access request plugins to point to the main Teleport repo and official docs

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#29651]
## Applies To

The various README.md files in https://github.com/gravitational/teleport-plugins can be problematic. Sometimes they have more information than their counterpart in this repo. Other times they will be outdated or have other issues.

Given that the access plugins themselves will be moving out of the teleport-plugins repo, any info in their corresponding README.md should be ported over to the corresponding docs page in this repo.

The plugin helm charts that are in the teleport-plugins repo can also have issues. Whether those charts will be ported to this repo or not, I think they should have an extremely minimal README.md that points to their corresponding chart reference doc on goteleport.com/docs and any other relevant docs.

## Details

Considering the pagerduty plugin, these are the locations where info can be found:

* [chart reference doc](https://goteleport.com/docs/reference/helm-reference/teleport-plugin-pagerduty/)
* [plugin guide doc](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-pagerduty/)
* [chart readme](https://github.com/gravitational/teleport-plugins/blob/v13.2.3/charts/access/pagerduty/README.md)
  * has an incorrect role (it was correct as of Teleport 6.2.x)
  * has a misleading typo in its toml example.
  * chart reference table that is not as good as the one in the official docs.
* [plugin readme](https://github.com/gravitational/teleport-plugins/blob/v13.2.3/access/pagerduty/README.md)
  * has additional information not in the guide, like [how to set up a pagerduty notification alert](https://github.com/gravitational/teleport-plugins/blob/v13.2.3/access/pagerduty/README.md#setting-up-pagerduty-notification-alerts)
  * has an incorrect role (it was correct as of Teleport 6.2.x)
  * outdated information about version compatibility
  * outdated download URLs/versions

The other plugins may have similar discrepancies between the various places.

## How will we know this is resolved?

All the docs for the plugins in this repo.

## Related Issues

https://github.com/gravitational/teleport-plugins/issues/852
https://github.com/gravitational/teleport-plugins/pull/839

```[tasklist]
### Tasks
- [x] Top-level README.md
- [ ] https://github.com/gravitational/teleport-plugins/pull/932
- [x] Access directory README.md
- [ ] https://github.com/gravitational/teleport-plugins/pull/933
- [x] [Discord](https://goteleport.com/docs/ver/15.x/access-controls/access-request-plugins/ssh-approval-discord/) - Add Docker image to installation & run in official documentation
- [ ] https://github.com/gravitational/teleport-plugins/pull/934
- [ ] https://github.com/gravitational/teleport/pull/32886
- [x] [Email](https://goteleport.com/docs/ver/15.x/access-controls/access-request-plugins/ssh-approval-email/) - Add Docker image to installation & run in official documentation
- [ ] https://github.com/gravitational/teleport-plugins/pull/938
- [ ] https://github.com/gravitational/teleport/pull/33239
- [ ] [JIRA](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-jira/) - Add Docker image to installation & run in official documentation, Jira Cloud, Jira Server
- [ ] https://github.com/gravitational/teleport-plugins/pull/939
- [ ] https://github.com/gravitational/teleport/pull/29827
- [ ] https://github.com/gravitational/teleport/pull/33327
- [x] [Mattermost](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-mattermost/) - Add Docker image installation & run in official documentation, ~sandbox~, ~workflow~
- [ ] https://github.com/gravitational/teleport-plugins/pull/940
- [ ] https://github.com/gravitational/teleport/pull/33328
- [x] [Microsoft Teams](https://goteleport.com/docs/ver/15.x/access-controls/access-request-plugins/ssh-approval-msteams/) - Add Docker image installation & run in official documentation, bot and app configuration
- [ ] https://github.com/gravitational/teleport-plugins/pull/941
- [ ] https://github.com/gravitational/teleport/pull/33326
- [ ] [PagerDuty](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-pagerduty/) - Add Docker image installation & run in official documentation, API, notification, auto-approval
- [ ] https://github.com/gravitational/teleport-plugins/pull/942
- [ ] https://github.com/gravitational/teleport/pull/33334
- [x] [Slack](https://goteleport.com/docs/access-controls/access-request-plugins/ssh-approval-slack/) Add Docker image installation & run in official documentation
- [ ] https://github.com/gravitational/teleport-plugins/pull/943
- [ ] https://github.com/gravitational/teleport/pull/33330
```

**Comment by ptgott** [comment]
Closing as complete
