### ISSUE TITLE
Unified resource pinning

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#30418]
Add the ability to pin your favorite resources, making them easily accessible in the web UI.
```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/31264
- [ ] https://github.com/gravitational/teleport/issues/32008
- [ ] https://github.com/gravitational/teleport/issues/32075
```

**Comment by zmb3** [comment]
Closing this one out - the work has been completed.
