### ISSUE TITLE
Teleport Connect - Unified Resources view

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#30422]
Teleport Connect should migrate to the unified resources view introduced in Teleport 14.
```[tasklist]
### Tasks
- [x] Add a gRPC endpoint that calls `authClient.ListUnifiedResources` https://github.com/gravitational/teleport/pull/33150
- [x] Move `teleport/UnifiedResources` to `shared/UnifiedResources` https://github.com/gravitational/teleport/pull/33635
- [x] Make `UnifiedResources` component reusable https://github.com/gravitational/teleport/pull/33635
- [x] Implement a layer between teleport UI <-> Unified Resources (we almost have it) and Connect UI <-> Unified Resources https://github.com/gravitational/teleport/pull/33917 https://github.com/gravitational/teleport/pull/33916
- [x] Integrate the resources search with the search bar https://github.com/gravitational/teleport/pull/34783
- [x] Add support for resource pinning https://github.com/gravitational/teleport/pull/35139
- [x] Return server's `subKind` from tshd https://github.com/gravitational/teleport/pull/34252
- [x] Remove old resources components https://github.com/gravitational/teleport/pull/34065
- [x] Make 'Copy to clipboard' feature work in Connect https://github.com/gravitational/teleport/pull/35049
- [x] Refactor the `useKeyBasedPagination.fetch` beacuse refreshing resources after Connect My Computer setup is done sometimes doesn't work. See comment: https://github.com/gravitational/teleport/pull/33916#discussion_r1385201086 https://github.com/gravitational/teleport/pull/35313
```
```[tasklist]
### Minor
- [ ] Hide scrollbar when the items are loading (setting `position: absolute` on the resources container should do the trick).
- [x] Decrease loading timeout from 400 ms to 150 ms
- [ ] Improve rendering preformance of the resources list in Connect (`React.memo` should help)
```
### Details on making `UnifiedResrouces` reusable
Currently, the resource grid component expects a [`UnifiedResources` type](https://github.com/gravitational/teleport/blob/10453b97e5c62c7372d6a691f1ea6f286b18868e/web/packages/teleport/src/services/agents/types.ts#L27) which is a union of all Web UI resource types. Then the conditional logic in the child components [renders different cards based on the resource type](https://github.com/gravitational/teleport/blob/10453b97e5c62c7372d6a691f1ea6f286b18868e/web/packages/teleport/src/UnifiedResources/ResourceCard.tsx#L352).

This poses some problems for Connect:
* Connect uses different resource types than Web UI. 
For example, compare Web UI `Database` type: https://github.com/gravitational/teleport/blob/10453b97e5c62c7372d6a691f1ea6f286b18868e/web/packages/teleport/src/services/databases/types.ts#L37  
with Connect `Database` type: https://github.com/gravitational/teleport/blob/10453b97e5c62c7372d6a691f1ea6f286b18868e/gen/proto/js/teleport/lib/teleterm/v1/database_pb.d.ts#L48
It means that we can't simply assign one type to the another.
* Action buttons on the cards trigger different actions than in Web UI and get data from different sources. 
For example, clicking _Connect_ for database in Web UI only opens a dialog, while in Connect app it shows a list of logins and then starts a db proxy.

#### What should we do?
* The resources grid component shouldn’t be aware of what it is rendering. The function that fetches a resource should simply return a structure describing the appearance of a single card. The responsibility for creating the correct card for a given resource type should be moved over from the child to the parent. Proposed type:
```ts
interface UnifiedResourceCard {
  id: string;
  name: string;
  description: {
    primary: string;
    secondary?: string;
  };
  labels: ResourceLabel[];
  resIcon: ResourceIconName;
  ResTypeIcon: typeof Icon;
  ActionButton: JSX.Element;
}
```
In order to make cards for the same resource type look the same for Connect and Web UI, we will create factory functions to generate resource objects:
```ts
function makeUnifiedResourceDatabaseCard(opts: {
  id: string;
  name: string;
  type: string;
  description: string;
  protocol: DbProtocol;
  labels: ResourceLabel[];
  ActionButton: JSX.Element;
}): UnifiedResourceCard {
  return {
    id: opts.id,
    name: opts.name,
    ResTypeIcon: DatabasesIcon,
    resIcon: databaseIconName(opts.protocol),
    ActionButton: opts.ActionButton,
    labels: opts.labels,
    description: { primary: opts.type, secondary: opts.description },
  };
}
```
* The component for sorting/filtering should not dependent on Web UI APIs. 
It should only receive state and callbacks to update the state. Unfortunately, now they also get things like `replaceHistory` or `pathname`. We don’t have such concepts in Connect (as we don't use browser history), but what is more important, these values are redundant and reveal too much internal details (we [already have TODOs](https://github.com/gravitational/teleport/blob/10453b97e5c62c7372d6a691f1ea6f286b18868e/web/packages/teleport/src/UnifiedResources/FilterPanel.tsx#L66) to fix them).

**Comment by avatus** [comment]
> The resources grid component shouldn’t be aware of what it is rendering.

With the upcoming List View for unified resources, we will either have to repeat the sentence but with "the resources list component shouldn't be aware of what it is rendering, or we can abstract it one level further into something like ResourceGrid and ResourceList. I'm ok with either.

I don't think the list view and card view "items" would have any different functionality. 

> The component for sorting/filtering should not dependent on Web UI APIs.

agreed. we can move these web specific functions into callbacks and pass them in when needed. I suppose that would happen when you move it to the shared folder. 

Resource pinning is about to be merged and will have to be handled as well, although that work is caught up in PRs atm. I haven't looked into how user preferences work with Connect. There is no new endpoints for the web work, only adding a field to update. However, the old user preferences in web would only pull on login for all clusters (root/leafs... leaves?) and I'm sure Connect did the same. now we need to pull pinned resource IDs per cluster so we'd have to do that individually per cluster logged in. All of the unified view came before pinning so it can probably happen in that sequence here too.

**Comment by gzdunek** [comment]
>With the upcoming List View for unified resources, we will either have to repeat the sentence but with "the resources list component shouldn't be aware of what it is rendering,

Now that I think of it, I'm a little less sure about my data model. Interface `UnifiedResourceCard` makes sense, but only for the cards view, not necessarily for the list.
Abstracting it one level further into something like `ResourceGrid` and `ResourceList` could work, but then the callers would need to re-create the layout on their own and put the components there, map the data for each view separately, whereas it would be more convenient to just import something like `<UnifiedResourceGridAndList />` 😏. 

>I don't think the list view and card view "items" would have any different functionality.

From what I see, the list item has only one icon, while the card has two. It's not a big difference and theoretically we could use `UnifiedResourceCard` interface also for list items, but there may be more changes in the future.

Also, it seems to me that my assumption that the unified resources component doesn't need to know what it is rendering was wrong. For example, currently the ID field is used only as a key to render a collection. For Web UI, I planned to generate it with [`resourceKey()`](https://github.com/gravitational/teleport/blob/5454ae0e55d99d988c119e071c77611fe5ef5215/web/packages/teleport/src/UnifiedResources/Resources.tsx#L184) function and for Connect use `resourceUri` which is already unique. 
However, this changes with the resource pinning, where we are required to use the same ids for backend, web UI and Connect. Because of that, we shouldn't allow any "string" as an ID. 

To sum up: I'm thinking of keeping the current `UnifiedResources` type, but instead of having a union of all Web UI resource types, it would be a union of "minimal" resource definitions, with only those properties needed to render card/list items.
Something like this:
```ts
export interface UnifiedResource {
  resource:
    | UnifiedResourceApp
    | UnifiedResourceDatabase
    | UnifiedResourceNode
    | UnifiedResourceKube
    | UnifiedResourceDesktop
    | UnifiedResourceWindowsDesktopService
    | UnifiedResourceUserGroup;
  ui: {
    ActionButton: JSX.Element;
  };
}
```

>I haven't looked into how user preferences work with Connect. There is no new endpoints for the web work, only adding a field to update. However, the old user preferences in web would only pull on login for all clusters (root/leafs... leaves?) and I'm sure Connect did the same.

Currently Connect doesn't fetch user preferences at all, so we will have to add an endpoint. 

>now we need to pull pinned resource IDs per cluster so we'd have to do that individually per cluster logged in. 

So after switching to some leaf cluster, we will have to fetch pinned resources for it, correct?

**Comment by avatus** [comment]
Now that I've come across it, having the `ActionButton` be a prop is immensely helpful for Unified Access Requests too, because that action button can be easily changed to Add/Remove to request. Love it
