### ISSUE TITLE
Teleport Connect - App Access support

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#30421]
Acceptance criteria:
- [x] Users can configure local tunnels for both types of apps, which show up in the connection picker like any other tunnel.
- [x] Teleport Connect shows both web apps and TCP apps in the resource listing (cluster resources & access requests).
- [x] Docs are updated to mention app support.
- [x] Teleport Connect allows "launching" an app which opens it in the browser. (You may be asked to log in if you don't have a valid web session).
   - [ ] Corner case: ensure that the user in the Web UI (if already logged in) matches the user who was logged in to Teleport Connect
- [x] Apps can be accessed via search bar integration.
   - Web apps - launch via browser.
   - TCP apps - start local tunnel.

```[tasklist]
### Tasks
- [x] https://github.com/gravitational/teleport/pull/36224
- [ ] https://github.com/gravitational/teleport.e/pull/3151
- [ ] https://github.com/gravitational/teleport/issues/35959
- [ ] https://github.com/gravitational/teleport/pull/36557
- [ ] https://github.com/gravitational/teleport/pull/37177
- [ ] https://github.com/gravitational/teleport/issues/35554
- [ ] https://github.com/gravitational/teleport/issues/35557
- [ ] https://github.com/gravitational/teleport/pull/36520
```
