### ISSUE TITLE
Ease AWS OIDC Integration set up

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#30447]
What would you like Teleport to do?
Ease the set up of AWS OIDC Integration by providing a single command for users to run and set up everything.

What problem does this solve?
Reduce the amount of time it takes to set up from minutes to seconds.
Reduce the complexity it takes from dozens of clicks and copy/paste to 4 actions (copy command, click on link to cloud shell, paste command and run it)

If a workaround exists, please include it.
Keep using the current flow.
```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/31521
- [ ] https://github.com/gravitational/teleport/pull/31656
- [ ] AWS OIDC - UI: Update Set Up Integration flow `https://.../awsoidc-idp.sh` configure script
- [ ] AWS OIDC - UI: Update Enroll RDS to use `https://.../listdatabases-iam.sh` configure script
- [ ] https://github.com/gravitational/teleport/pull/34036
```
