### ISSUE TITLE
AWS OIDC DeployService: allow Security Group Selection

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#30622]
What would you like Teleport to do?
DeployService starts a new teleport process in a container (ECS Service).
This ECS Service has an associated Security Group.
Currently this value is implicit, and it uses the VPC's default Security Group.
This default SG might not be the best one to choose from.
We should still default to this SG, but let users decide which ones to pick from.

What problem does this solve?
Some operators restrict the default SG access, so that new resources are "blocked" until they are assigned a specific SG.
Allowing the user to pick a SG should let them keep the default one restricted, but still allow connectivity between Teleport Proxy and Database Service.

If a workaround exists, please include it.
Change the default SG to allow outbound access.

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/30866
- [ ] https://github.com/gravitational/teleport/pull/30971
- [ ] https://github.com/gravitational/teleport/pull/30968
- [ ] https://github.com/gravitational/teleport/pull/32885
```

**Comment by marcoandredinis** [comment]
This is now complete (backport PRs were created)
