### ISSUE TITLE
4.2 Features Documentation.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3133]
This ticket is to track 4.2 features that'll be in this release. 

Admin Tasks:
- [x] Fork Docs and create 4.2 ( to be done after I merge in last FIPS Update )

New Features to Document:

_In Alpha_
- [x] Workflow API |  Issue: https://github.com/gravitational/teleport/issues/3006  Docs: https://github.com/gravitational/teleport/pull/3155 
- [x] Enhanced Session Recording |  Issue: https://github.com/gravitational/teleport/issues/2948 Docs:  #3187 

_In Beta_
- [x] GCP Stateless HA Support via Firestone and GCS https://github.com/gravitational/teleport/pull/2821

_GA_
- [x] Remote tctl execution. #2991
- [x] Support for G Suite Service Accounts https://github.com/gravitational/teleport/pull/3122 

Release Notes:
Bug Fixes:
- Bug in socks4 when rendering remote address https://github.com/gravitational/teleport/pull/3110 

Misc:
- Adopting root/leaf for trusted clusters https://github.com/gravitational/teleport/issues/3007
- Documented Teleport FedRAMP / FIPS Support https://github.com/gravitational/teleport/issues/3097 

## Release Notes:
Alpha Features:
- Workflows API let's admins escalate RBAC roles . https://gravitational.com/teleport/docs/enterprise/#approval-workflows
- Enhanced Session Recording let's you know what's really happening during a Teleport Session https://gravitational.com/teleport/docs/features/enhanced_session_recording/ 

Beta Features:
-  Teleport provides HA Support using Firestone and Google Cloud Storage using Google Cloud Platform. https://gravitational.com/teleport/docs/gcp_guide/

Bug Fix: Fixed issue in  socks4 when rendering remote address https://github.com/gravitational/teleport/pull/3110 

Other: 
Adopting root/leaf terminology for trusted clusters. https://gravitational.com/teleport/docs/trustedclusters/ 
Documented Teleport FedRAMP / FIPS Support  https://gravitational.com/teleport/docs/enterprise/ssh_fips/

**Comment by benarent** [comment]
@wadells @fspmarshall I've added release notes at the bottom. I'll fix the link tomorrow once I deploy 4.2 docs in the morning. I'll need to do a bit more with the formatting but we should be good to go.
