### ISSUE TITLE
Provide a way to manage Teleport join tokens via web UI

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#31671]
## What would you like Teleport to do?

Provide a way to manage Teleport join tokens via web UI. See currently active tokens, the services they allow, their expiry time, add new ones, delete old ones, etc.

## What problem does this solve?

With the newer Teleport Discover wizards, most people are using automatically generated tokens that are completely abstracted away from them. When they want to add another service to their running agent, they suddenly get plunged into a world of hurt needing to log in and use `tctl` remotely which is an unfamiliar environment for them.

## If a workaround exists, please include it.

Use `tctl` and ask support for help.

## Task breakdown:

- [x] Create apiserver routes for JoinTokens CRUD
- [x] UI/UX for the web component (prototype done by @avatus , feedback from kenny after)
- [x] Final updates/adjustments to web UI

**Comment by webvictim** [comment]
(I couldn't find a duplicate issue for this if one exists, sorry)
