### ISSUE TITLE
Discover tile for Connect My Computer

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#32185]
When setting up the cluster for the first time, we nudge the user towards adding a new resource. Many people decide to add their own device first just to try things out.

Connect My Computer simplifies this flow, but the user needs to be aware of it. This is what the Discover tile for Connect My Computer tries to accomplish.

* [Designs](https://www.figma.com/file/uLevdNsEnIvvLDSZ9sQqXM/Discover-Access?type=design&node-id=1337%3A5040&mode=design&t=Pd93duvXW3us6ZGO-1)
* [Mapped out flow](https://www.figma.com/file/7TgKoTyO4gvxdqOToD9f5n/Interaction-Diagrams?type=whiteboard&node-id=802%3A1669&t=SPciHeltWYBQehGE-1)

--- 

```[tasklist]
### Prerequisites
- [ ] https://github.com/gravitational/teleport/issues/32186
- [ ] https://github.com/gravitational/teleport/issues/32187
```

```[tasklist]
### Connect
- [x] Add electron-builder config for the custom protocol
- [ ] https://github.com/gravitational/teleport/issues/32188
```

```[tasklist]
### Web UI
- [ ] https://github.com/gravitational/teleport/issues/32190
- [ ] https://github.com/gravitational/teleport/issues/32191
- [ ] https://github.com/gravitational/teleport/pull/34288
- [ ] https://github.com/gravitational/teleport/issues/32192
- [ ] https://github.com/gravitational/teleport/issues/32206
- [ ] https://github.com/gravitational/teleport/pull/35131
```

Shortcuts / tech debt:

* The empty state copy in Connect does not link to Discover in Web UI because of considerable amount of work needed to allowlist Web UI URL, see [#33144](https://github.com/gravitational/teleport/pull/33144).
