### ISSUE TITLE
MFA for Admin Actions: tracker

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#33767]
[RFD 131](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#administrative-actions)

## Status
- [ ] https://github.com/gravitational/teleport/pull/30203
  - [ ] Extend retry with MFA logic to WebUI
  - [ ] Extend retry with MFA logic to Teleport Connect
- [ ] https://github.com/gravitational/teleport/pull/33676/
- [ ] [Infer MFA Requirement](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#infer-mfa-requirement) before making a request
  - [ ] `tctl` and `tsh`
  - [ ] WebUI
  - [ ] Teleport Connect
  - [ ] [Prompt for MFA before edits with `tctl edit`](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#editing-resources)
- [ ] [Convert HTTP admin actions to gRPC](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#http-endpoints)
- [ ] Add Touch ID support to `tctl`
- [ ] [Add Audit events](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#audit-events)
- [ ] [Add PostHog events](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#product-usage)
- [ ] Convert all [admin actions](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md#administrative-actions) to require MFA
- [ ] Update testplan
- [ ] Add docs
