### ISSUE TITLE
Machine ID: Q4 Bot Management Epic

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#34299]
An epic focussing on improving the management story for Machine ID Bots. The key goal of this epic is to surface Bot's properly within the Teleport UI - to improve the discoverability of Machine ID but also to reduce the complexity in managing Bots for users less familiar with Teleport. 

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/issues/33808
- [ ] https://github.com/gravitational/teleport/issues/34260
- [ ] https://github.com/gravitational/teleport/issues/34262
- [ ] https://github.com/gravitational/teleport/issues/31671
- [ ] https://github.com/gravitational/teleport/issues/34300
- [ ] https://github.com/gravitational/teleport/issues/34285
```

**Comment by strideynet** [comment]
The story around what we want to do for Join Tokens/Bot Creation is a little loose - either we approach join token creation from a general CRUD List/Create with YAML resource - or we approach this from a "wizard" flow that's more discover-esque that flows from the Bot creation to the Token creation and is more guided.

**Comment by zmb3** [comment]
@strideynet should we close this?
