### ISSUE TITLE
Reorganize the steps of Connect My Computer setup to account for scoped Webauthn credentials

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#34531]
During the setup of Connect My Computer, Connect runs `RoleSetup` and `TokenProvisioner`. Those two structs are called through separate RPCs and they create or update a role, optionally update a user object if the current user doesn't have that new role already and also create a new join token.

After [RFD 131 Administrative Actions MFA](https://github.com/gravitational/teleport/blob/master/rfd/0131-adminitrative-actions-mfa.md) gets implemented, setting up Connect My Computer in our Cloud will require three key taps to authorize those three actions. [RFD 155 Scoped Webauth Credentials](https://github.com/gravitational/teleport/pull/35185) aims to limit this to just one tap by allowing reuse of MFA credentials for up to 5 minutes.

Scoped credentials save us a lot of work by not forcing us to refactor all actions to happen within a single RPC in the auth server. However, we still have to adjust the setup steps to account for that limit of 5 minutes.

## How the setup behaves at the moment

<img width="576" alt="Connect My Computer setup" src="https://github.com/gravitational/teleport/assets/27113/4a23dd22-25da-4705-b523-7ae7fb591d04">

The role and the user are updated during step 1. The token is created during step 3. If the download takes more than 5 minutes, step 3 will fail. Clicking "Retry" will remove the downloaded binary (#34844), so then we risk a situation where the user won't be able to complete the setup.

## How the setup will have to behave

The steps can remain the same, the only thing we need to change is the download step which must become the first step. If it's done first, the download can take however long is needed because at this point the MFA creds have not been issued yet.

At this step we should also run `teleport version` just to check if the binary can be executed. This has a number of benefits:
   * It checks if the download has not been corrupted.
   * It forces the OS (macOS in particular) to run checks on the binary which can take a couple of seconds. This way were not racing against MFA creds expiration as we would if the first run happened later.

## Other administrative actions

Those are not the only administrative actions performed from Connect My Computer.

### Delete token

During the setup, after the node joins the cluster, we attempt to remove the token. This is because [Teleport currently doesn't support single-use tokens](https://github.com/gravitational/teleport/issues/7133). We can just get rid of the code that does it and depend on the TTL. The alternative is to require another tap which just seems like a hassle from the UX side.

### Delete node

Selecting "Remove agent" in the Connect My Computer status view stops the agent process and attempts to remove the agent. This is done so that it doesn't linger in the cache.

In that instance, we can keep doing this as it's the only administrative action performed during agent removal.

## TODO

* [x] Make downloading the first step.
* [x] Check agent version after download.
* [x] Remove code which calls `connectmycomputer.TokenProvisioner.DeleteToken`.
* [x] [Use `CreateRole` over `UpsertRole` where possible](https://gravitational.slack.com/archives/C03FJA391M3/p1698932892634719?thread_ts=1698932487.828959&cid=C03FJA391M3).
  * https://github.com/gravitational/teleport/pull/37324
