### ISSUE TITLE
4.3 - Manual Test Plan 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3581]
## Manual Testing Plan

Below are the items that should be manually tested with each release of Teleport.
These tests should be run on both a fresh install of the version to be released
as well as an upgrade of the previous version of Teleport.

- [x] Adding nodes to a cluster
  - [x] Adding Nodes via Valid Static Token
  - [x] Adding Nodes via Valid Short-lived Tokens
  - [x] Adding Nodes via Invalid Token Fails
  - [x] Revoking Node Invitation

- [x] Labels
  - [x] Static Labels
  - [x] Dynamic Labels

- [ ] Trusted Clusters
  - [x] Adding Trusted Cluster Valid Static Token
  - [x] Adding Trusted Cluster Valid Short-lived Token
  - [ ] Adding Trusted Cluster Invalid Token
  - [ ] Removing Trusted Cluster

- [x] RBAC - @awly 

  Make sure that invalid and valid attempts are reflected in audit log.

  - [x] Successfully connect to node with correct role
  - [x] Unsuccessfully connect to a node in a role restricting access by label
  - [x] Unsuccessfully connect to a node in a role restricting access by invalid SSH login
  - [x] Allow/deny role option: SSH agent forwarding
  - [x] Allow/deny role option: Port forwarding

- [ ] Users
With every user combination, try to login and signup with invalid second factor, invalid password to see how the system reacts.

  - [x] Adding Users Password Only
  - [x] Adding Users OTP
  - [x] Adding Users U2F
  - [x] Login Password Only
  - [x] Login OTP
  - [x] Login U2F
  - [x] Login OIDC
  - [x] Login SAML
  - [x] Login GitHub
  - [x] Deleting Users

- [x] Backends @russjones  
  - [x] Teleport runs with etcd
  - [x] Teleport runs with dynamodb
  - [x] Teleport runs with boltdb
  - [x] Teleport runs with dir

- [x] Session Recording @webvictim 
  - [x] Session recording can be disabled
  - [x] Sessions can be recorded at the node
    - [x] Sessions in remote clusters are recorded in remote clusters
  - [x] Sessions can be recorded at the proxy
    - [x] Sessions on remote clusters are recorded in the local cluster
    - [x] Enable/disable host key checking.

- [ ] Audit Log @benarent 
  - [x] Failed login attempts are recorded
  - [x] Interactive sessions have the correct Server ID
    - [x] Server ID is the ID of the node in regular mode
    - [x] Server ID is randomly generated for proxy node
  - [x] Exec commands are recorded
  - [x] `scp` commands are recorded
  - [x] Subsystem results are recorded

- [x] Interact with a cluster using `tsh` @russjones 

   These commands should ideally be tested for recording and non-recording modes as they are implemented in a different ways.

  - [x] tsh ssh \<regular-node\>
  - [x] tsh ssh \<regular-iot\>
  - [x] tsh ssh \<node-remote-cluster\>
  - [x] tsh ssh \<node-iot-remote-cluster\>
  - [x] tsh ssh -A \<regular-node\>
  - [x] tsh ssh -A \<regular-iot-node\>
  - [x] tsh ssh -A \<node-remote-cluster\>
  - [x] tsh ssh -A \<node-iot-remote-cluster\>
  - [x] tsh ssh \<regular-node\> ls
  - [x] tsh ssh \<regular-iot-node\> ls
  - [x] tsh ssh \<node-remote-cluster\> ls
  - [x] tsh ssh \<node-iot-remote-cluster\> ls
  - [x] tsh ssh -L \<regular-node\>
  - [x] tsh ssh -L \<regular-iot-node\>
  - [x] tsh ssh -L \<node-remote-cluster\>
  - [x] tsh ssh -L \<node-iot-remote-cluster\>
  - [x] tsh scp \<regular-node\>
  - [x] tsh scp \<regular-iot-node\>
  - [x] tsh scp \<node-remote-cluster\>
  - [x] tsh scp \<node-iot-remote-cluster\>
  - [x] tsh join \<regular-node\>
  - [x] tsh join \<regular-iot-node\>
  - [x] tsh join \<node-remote-cluster\> **See https://github.com/gravitational/teleport/issues/3891**
  - [x] tsh join \<node-iot-remote-cluster\> **See https://github.com/gravitational/teleport/issues/3891**
  - [x] tsh play \<regular-node\>
  - [x] tsh play \<node-remote-cluster\> **See https://github.com/gravitational/teleport/issues/3894**
  - [x] tsh ls
  - [x] tsh clusters

- [x] Interact with a cluster using `ssh` @awly 
   Make sure to test both recording and regular proxy modes.
  - [x] ssh \<regular-node\>
  - [x] ssh \<node-remote-cluster\>
  - [x] ssh -A \<regular-node\>
  - [x] ssh -A \<node-remote-cluster\>
  - [x] ssh \<regular-node\> ls
  - [x] ssh \<node-remote-cluster\> ls
  - [x] scp \<regular-node\>
  - [x] scp \<node-remote-cluster\>
  - [x] ssh -L \<regular-node\>
  - [x] ssh -L \<node-remote-cluster\>

- [x] Interact with a cluster using the Web UI @fspmarshall 
  - [x] Connect to a Teleport node
  - [x] Connect to a OpenSSH node
  - [x] Check agent forwarding is correct based on role and proxy mode.

### Combinations - @webvictim 

For some manual testing, many combinations need to be tested. For example, for
interactive sessions the 12 combinations are below.

- [x] Connect to a OpenSSH node in a local cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a local cluster using Teleport.
- [x] Connect to a OpenSSH node in a local cluster using the Web UI.
- [x] Connect to a Teleport node in a local cluster using OpenSSH.
- [x] Connect to a Teleport node in a local cluster using Teleport.
- [x] Connect to a Teleport node in a local cluster using the Web UI.
- [x] Connect to a OpenSSH node in a remote cluster using OpenSSH.
- [x] Connect to a OpenSSH node in a remote cluster using Teleport.
- [x] Connect to a OpenSSH node in a remote cluster using the Web UI.
- [x] Connect to a Teleport node in a remote cluster using OpenSSH.
- [x] Connect to a Teleport node in a remote cluster using Teleport.
- [x] Connect to a Teleport node in a remote cluster using the Web UI.

### Teleport with EKS/GKE @benarent 

* [x] Deploy Teleport on a single EKS cluster
* [x] Deploy Teleport on two EKS clusters and connect them via trusted cluster feature
* [ ] Deploy Teleport Proxy outside of GKE cluster fronting connections to it (this feature is not yet supported for EKS)

### Teleport with FIPS mode @awly 

* [x] Perform trusted clusters, Web and SSH sanity check with all teleport components deployed in FIPS mode.

### Migrations @fspmarshall 

* [x] Migrate trusted clusters from 4.1.0 to 4.2.0
  * [x] Migrate auth server on main cluster, then rest of the servers on main cluster
        SSH should work for both main and old clusters
  * [x] Migrate auth server on remote cluster, then rest of the remote cluster
       SSH should work

### Command Templates 

When interacting with a cluster, the following command templates are useful:

#### OpenSSH

```
# when connecting to the recording proxy, `-o 'ForwardAgent yes'` is required.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# the above command only forwards the agent to the proxy, to forward the agent
# to the target node, `-o 'ForwardAgent yes'` needs to be passed twice.
ssh -o "ForwardAgent yes" \
  -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p" \
  node.example.com

# when connecting to a remote cluster using OpenSSH, the subsystem request is
# updated with the name of the remote cluster.
ssh -o "ProxyCommand ssh -o 'ForwardAgent yes' -p 3023 %r@proxy.example.com -s proxy:%h:%p@foo.com" \
  node.foo.com
```

#### Teleport

```
# when connecting to a OpenSSH node, remember `-p 22` needs to be passed.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -p 22 node.example.com

# an agent can be forwarded to the target node with `-A`
tsh --proxy=proxy.example.com --user=<username> --insecure ssh -A -p 22 node.example.com

# the --cluster flag is used to connect to a node in a remote cluster.
tsh --proxy=proxy.example.com --user=<username> --insecure ssh --cluster=foo.com -p 22 node.foo.com
```

### Teleport with SSO Providers @benarent 

- [x] Github install instructions work
    - [x] Github Screenshots are up to date
- [x] G Suite install instructions work
    - [x] G Suite Screenshots are up to date
- [ ] ActiveDirectoy install instructions work
    - [ ] Active Directoy Screenshots are up to date
- [x] Okta install instructions work    
    - [x] Okta Screenshots are up to date
- [x] OneLogin install instructions work    
    - [x] OneLogin Screenshots are up to date
- [x] OIDC install instructions work    
    - [x] OIDC Screenshots are up to date

### Teleport Plugins @benarent 

- [x] Test receiving a message via Teleport Slackbot 
- [x] Test receiving a new Jira Ticket via Teleport Jira 
    
#### Top Nav
- [x] Verify that user name is displayed.
- [x] Verify that user menu shows a logout button.

#### Cluster List
- [x] Verify that root cluster is displayed with the proper label.
- [x] Verify that "Name", "Version", "Nodes" and "Public URL" shows the correct information.
- [x] Verify that column sorting works.
- [x] Verify that cluster "View" button works as a hyperlink by opening a new browser tab.
- [x] Verify that search works.

#### Top Nav
- [x] Verify that user name is displayed.
- [x] Verify that Breadcrumb Navigation has a link to dashboard.
- [x] Verify that cluster name is displayed.
- [x] Verify that clicking on Teleport logo navigates to the Dashboard.

#### Side Nav
- [x] Verify that "Nodes" item is highlighted.
- [x] Verify that each item has an icon.

#### Nodes
- [x] Verify that "Nodes" table shows all joined nodes.
- [x] Verify that "Connect" button shows a list of available logins.
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values.
- [x] Verify that "Search" works.
- [x] Verify that terminal opens when clicking on one of the available logins.

#### Active Sessions
- [x] Verify that "empty" state is handled.
- [x] Verify that it displays the session when session is active.
- [x] Verify that "Description", "Session ID", "Users", "Nodes" and "Duration" columns show correct values.
- [x] Verify that "OPTIONS" button allows to join a session.

#### Audit log
- [x] Verify that Audit log has "Sessions" and "Events" tabs where "Sessions" is active by default.
- [ ] Verify that time range button is shown and works.

#### Audit log (Sessions)
- [x] Verify that Sessions table shows the correct session values.
- [x] Verify that Play button opens a session player.
- [x] Verify that search works (it should do a search on all table cells).

#### Auth Connectors.
- [x] Verify that creating OIDC/SAML/GITHUB connectors works.
- [x] Verify that editing  OIDC/SAML/GITHUB connectors works.
- [x] Verify that error is shown when saving an invalid YAML.
- [x] Verify that correct hint text is shown on the right side.

  Card Icons
  - [x] Verify that GITHUB card has github icon
  - [x] Verify that SAML card has SAML icon
  - [x] Verify that OIDC card has OIDC icon

#### Roles
- [x] Verify that roles are shown.
- [x] Verify that "Create New Role" dialog works.
- [x] Verify that deleting and editing works.
- [x] Verify that error is shown when saving an invalid YAML.
- [x] Verify that correct hint text is shown on the right side.

#### Trusted Clusters
- [x] Verify that adding/removing a trusted cluster works.
- [x] Verify that correct hint text is shown on the right side.

#### Help&Support
- [x] Verify that all URLs work and correct (no 404)

### Account
- [x] Verify that Account screen is accessibly from the user menu for local users.
- [x] Verify that changing a local password works (OTP, U2F)

### Terminal
- [x] Verify that top nav has a user menu (Dashboard and Logout).
- [x] Verify that switching between tabs works on alt+[1...9].

#### Node List Tab
- [x] Verify that Cluster selector works (URL should change too)
- [x] Verify that Quick access input works. It
- [x] Verify that Quick access input handles input errors.
- [x] Verify that "Connect" button shows a list of available logins.
- [x] Verify that "Hostname", "Address" and "Labels" columns show the current values.
- [x] Verify that "Search" works.
- [x] Verify that new tab is created when starting a session.

#### Session Tab
- [x] Verify that session and browser tabs both show the title with login and node name.
- [x] Verify that terminal resize works (use midnight commander (sudo apt-get install mc))
- [x] Verify that session tab shows a list of participants when a new user joins the session.
- [x] Verify that tab automatically closes on "$ exit" command.
- [x] Verify that SCP Upload works.
- [x] Verify that SCP Upload handles invalid paths and network errors.
- [x] Verify that SCP Download works.
- [x] Verify that SCP Download handles invalid paths and network errors.

### Session Player
- [x] Verify that it can replay a session.
- [x] Verify that scrolling behavior.
- [x] Verify that error message is displayed (use invalid SID)

### Invite Form
- [x] Verify that input validation.
- [x] Verify that invite works with 2FA disabled.
- [x] Verify that invite works with OTP enabled.
- [x] Verify that invite works with U2F enabled.
- [x] Verify that error message is shown if an invite is expired/invalid.

### Login Form
- [x] Verify that input validation.
- [x] Verify that login works with 2FA disabled.
- [x] Verify that login works with OTP enabled.
- [x] Verify that login works with U2F enabled.
- [x] Verify that login works for Github/SAML/OIDC.
- [x] Verify that account is locked after several unsuccessful attempts.
- [x] Verify that redirect to original URL works after successful login.

### RBAC
 Create the following role
```
  spec:
  allow:
    logins:
    - root
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
  deny:
    logins: null
  options:
    cert_format: standard
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
```
  - [ ] Verify that a user has access only to: "Cluster List", "Nodes", and "Active Sessions".

## Performance/Soak Test @fspmarshall 

Using `tsh bench` tool, perform the soak tests and benchmark tests on the following configurations:

- [x] Cluster with 10K nodes in normal (non-IOT) node mode with ETCD
- [x] Cluster with 10K nodes in normal (non-IOT) mode with DynamoDB

- [x] Cluster with 1K IOT nodes with ETCD
- [x] Cluster with 1K IOT nodes with DynamoDB

- [ ] Cluster with 500 trusted clusters with ETCD
- [ ] Cluster with 500 trusted clusters with DynamoDB

**Soak Tests** @awly 

- [x] Run 4hour soak test with a mix of interactive/non-interactive sessions:

```
tsh bench --duration=4h --threads=10 user@teleport-monster-6757d7b487-x226b ls
tsh bench --interactive --duration=4h --threads=10 user@teleport-monster-6757d7b487-x226b ps uax
```

- [x] Observe prometheus metrics for goroutines, open files, RAM, CPU, Timers and make sure there are no leaks

**Breaking load tests** @fspmarshall 

- [ ] Load system with tsh bench to the capacity and publish maximum numbers of concurrent sessions with interactive 
and non interactive tsh bench loads.

**Comment by awly** [comment]
Notes from soak testing:
- after starting the `tsh bench --interactive` there were a few errors due to running out of file descriptors due to default ulimit (1024):
```
ERRO [NODE]      Unable to create connection context: pipe2: too many open files. regular/sshserver.go:1027
``` 
this stops after a few minutes and the rest of the test goes without errors
- during the test, `teleport` allocated ~1.2GB of RAM; after the test stopped, this memory is not released back to the OS by the Go runtime. I confirmed there are no actual leaks via the different `go_memstats` entries

**Comment by fspmarshall** [comment]
Note from DynamoDB 10k test:  25 nodes (0.25%) froze during initial startup and never successfully joined the cluster (no timeout errors ever occurred).  I'm not 100% certain where they froze, but based on the final logs, it appears it was somewhere early in the startup process:

```
...
DEBU [AUTH]      Attempting to register through proxy server. auth/register.go:143
DEBU [CLIENT]    HTTPS client init(proxyAddr=example.com, insecure=false) client/weblogin.go:295
DEBU [AUTH]      Successfully registered through proxy server. auth/register.go:132
DEBU [PROC:1]    Deleted generated key pair Node first-time-connect. service/connect.go:242
INFO [PROC]      Node has obtained credentials to connect to cluster. service/connect.go:377
DEBU [PROC]      Attempting to connect to Auth Server directly. service/connect.go:795
DEBU [PROC]      Attempting to connect to Auth Server through tunnel. service/connect.go:803
DEBU [CLIENT]    HTTPS client init(proxyAddr=example.com, insecure=false) client/weblogin.go:295
DEBU [PROC]      Discovered address for reverse tunnel server: example.com. service/connect.go:883
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:222
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:137
```

Note that all 25 appear to have frozen in the same place.  Some of the nodes had `SLOW TRANSACTION` warnings from sqlite after this point, but since I've seen those warnings in some of the logs of nodes which didn't freeze, I don't think they are causally related.

**Comment by fspmarshall** [comment]
Note from DynamoDB 10k test: Cluster was generating 2-4x more writes against backend than I expected based on some back of the napkin math.  Not 100% certain that this is a bug, but it does merit further investigation.  I rolled back the cluster version to `4.2` latest and then to `4.1` latest.  Similar number of writes were present, so whether or not this is a bug, I don't consider it a `4.3` blocker since it is a preexisting phenomena.

**Comment by benarent** [comment]
Closing the test plan as we've issues tracked in other issues.

**Comment by zmb3** [comment]
👋 Hey @awly 

> during the test, teleport allocated ~1.2GB of RAM; after the test stopped, this memory is not released back to the OS by the Go runtime. I confirmed there are no actual leaks via the different go_memstats entries

I'm not convinced that there's not a leak in 4.3.x.  Are these tests something enterprise customers can run as well or do they depend on Gravitational tools/infrastructure?

**Comment by awly** [comment]
@zmb3 you can run soak tests with `tsh bench` against your own teleport setup, for example:

```
tsh login ...
tsh bench --duration=4h --threads=10 user@some-node ls
tsh bench --interactive --duration=4h --threads=10 user@some-node ps uax
```

It's possible there's a leak in certain setups, but not in the one I tested with. If you find something, please open a new issue with the details of your setup and your measurements.
