### ISSUE TITLE
File upstream PRs to fix dependency review for Rust crates

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#35993]
In https://github.com/gravitational/teleport/pull/26874/commits/6b2be07bfd1c4f6f2d19fd676ba21686675e827f we added some overrides for our license check, based on the failures in https://github.com/gravitational/teleport/actions/runs/7280939099/job/19840691057?pr=26874

![image](https://github.com/gravitational/teleport/assets/13578537/4c452a51-5375-4500-9a7c-71f2ae5b1b73)

Let's file upstream PRs to fix the license field in these repos so that the SPDX parser can comprehend it. (`ring` is an exception due to its non-standard license, that will need to remain an override and should be reviewed by legal.)
```[tasklist]
### Tasks
- [ ] https://github.com/rusticata/asn1-rs/pull/34
- [ ] https://github.com/rusticata/der-parser/pull/70
- [ ] https://github.com/dalek-cryptography/curve25519-dalek/pull/647
- [ ] https://github.com/Devolutions/sspi-rs/pull/225
- [ ] https://github.com/cloudflare/boring/pull/230
- [ ] `ring` review by legal
```
