### ISSUE TITLE
`tsh ssh` remote port forwarding umbrella ticket

### ISSUE THREAD

**Issue by atburke** [gravitational/teleport#37117]
Umbrella ticket for adding remote port forwarding support (equivalent to `ssh -R`) to Teleport.

```[tasklist]
### Tasks
- [x] Implement remote forwarding for `tsh` with the `-R` flag https://github.com/gravitational/teleport/pull/38829
- [x] Implement remote forwarding for regular SSH servers https://github.com/gravitational/teleport/pull/38828
- [x] Implement remote forwarding for OpenSSH servers https://github.com/gravitational/teleport/pull/38047
- [x] Update docs https://github.com/gravitational/teleport/pull/38942
- [x] Update testplan https://github.com/gravitational/teleport/pull/38942
```

Success criteria:

- Parity with `ssh -R`
- `tsh` can forward ports from both Teleport and OpenSSH nodes
- Teleport nodes can forward ports to both `tsh` and OpenSSH clients
- `tsh ssh -R` fails gracefully for nodes where remote port forwarding isn't supported
- Remote forwarding requires authorization and emits audit events just like local forwarding

**Comment by zmb3** [comment]
See #7776 for the original request (which we should close when this work completes)
