### ISSUE TITLE
Improve robustness and auditing of discovery service

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#37620]
## Description

When performing SSH auto-discovery on cloud providers, discovery service automatically installs Teleport on the discovered instances. It works in the successful scenario however when something fails (e.g. we fail to install Teleport package via SSM on EC2 instance) the experience is subpar:

- There is no good indication that some nodes failed to join and which ones and why.
- There is no clear way for a user to find out what failed and where to go to troubleshoot.
- There is no easy way for a user to retry the operation.
- Oftentimes Teleport would keep trying to reinstall and failing and it can't self-repair.

## Proposed solution(-s)

In the order of the required effort, I think these are the steps that we need to take to improve the reliability and observability of auto-discovery, focused specifically on SSH for now since that seems to be most fragile at the moment.

### Improve audit logging

As a cheap first step, let's make sure that all successes and failures of the discovery service are captured in the audit log. I _think_ we do have audit logs for it but let's reinspect them and make sure they're useful and in case of failure contain all required information for a user about:

- Which node installation failed on.
- Reason for the failure (e.g. install script error).
- Link to the relevant part of Cloud Console for troubleshooting (e.g. SSM execution logs for EC2).

### Make sure auto-discovery install/upgrade scripts can handle small problems

We should identify most common failure scenarios and make sure that the auto-discovery system and the install script can overcome them gracefully upon retry or once the issue has been resolved. Some examples that come to mind (but not exhaustive):

- Lack of IAM permissions (should also be clearly evident from audit log, to the point above).
- Installation failed part-way due to external issues (like, repos, networking, etc.).
- Installation failed due to bad config.

The system should detect that it failed to install before (as opposed to, for example, this being an installation done by something else) and take appropriate actions like uninstall and start from scratch.

### Make use of notification system

Auto-enrollment failures should be captured in our new notification system.

### Build auto-discovery dashboard
( see https://github.com/gravitational/teleport/issues/41909 )
I think this is what will be most useful for users but also require most engineering effort and design support but the idea is to have a dedicated dashboard that shows auto-discovery status where users can see/do things like:

- See whether auto-discovery is enabled, turn it on/off and update discovery config.
- See relevant auto-discovery status, for example nodes that fail to enroll and errors explaining why.
- Manually trigger "retry" (or "fix") on the nodes that failed.

Related issues:
https://github.com/gravitational/teleport/issues/31180
```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/41465
- [ ] https://github.com/gravitational/teleport/pull/41478
- [ ] https://github.com/gravitational/teleport/pull/41663
- [ ] https://github.com/gravitational/teleport/pull/41523
- [ ] https://github.com/gravitational/teleport/pull/41479
- [ ] https://github.com/gravitational/teleport/pull/41532
- [ ] https://github.com/gravitational/teleport/pull/41689
- [ ] https://github.com/gravitational/teleport/pull/41706
- [ ] https://github.com/gravitational/teleport/pull/44282
- [ ] https://github.com/gravitational/teleport/pull/44283
- [ ] https://github.com/gravitational/teleport/pull/44637
```

```[tasklist]
### Replace installation script with go code
- [ ] https://github.com/gravitational/teleport/pull/42614
- [ ] https://github.com/gravitational/teleport/pull/42621
- [ ] https://github.com/gravitational/teleport/pull/42633
- [ ] https://github.com/gravitational/teleport/pull/42857
- [ ] https://github.com/gravitational/teleport/pull/43029
- [ ] https://github.com/gravitational/teleport/pull/43234
- [ ] https://github.com/gravitational/teleport/pull/43423
- [ ] https://github.com/gravitational/teleport/pull/43466
```

**Comment by zmb3** [comment]
Everything in this tracking issue is marked complete and it hasn't been updated for 5 months so I'm assuming it's safe to close.
