### ISSUE TITLE
Implement Notifications System

### ISSUE THREAD

**Issue by rudream** [gravitational/teleport#37704]
Implement a notifications system that can be used to notify users of various events, updates, and warnings in real time.

This is a master ticket for the implementation of the notifications system outlined in [RFD 156](https://github.com/gravitational/teleport/blob/master/rfd/0156-notifications.md).

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/37707
- [ ] https://github.com/gravitational/teleport/pull/38327
- [ ] https://github.com/gravitational/teleport/pull/39616
- [ ] https://github.com/gravitational/teleport/pull/39715
- [ ] https://github.com/gravitational/teleport/pull/37706
- [ ] https://github.com/gravitational/teleport/pull/40263
- [ ] https://github.com/gravitational/teleport/pull/40264
- [ ] https://github.com/gravitational/teleport/pull/39942
- [ ] https://github.com/gravitational/teleport/pull/41321
- [ ] https://github.com/gravitational/teleport/pull/40941
- [ ] https://github.com/gravitational/teleport/pull/41621
- [ ] https://github.com/gravitational/teleport/pull/41662
- [ ] [Add `tctl` command for creating custom notifications](https://github.com/gravitational/teleport/pull/42124)
- [ ] Implement rate-limiting to limit # of notifications and prevent spikes in notification creation
- [ ] (Stretch) Implement websocket handler with watcher for real-time notifications
```

**Comment by zmb3** [comment]
Closing this tracking issue, the remaining few items will be wrapped up soon.
