### ISSUE TITLE
Use electron-builder's `notarize` config option for macOS target

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#38843]
It looks like [electron-builder now supports the `notarize` field](https://www.electron.build/configuration/mac.html#MacConfiguration-notarize) for the macOS target. It used to be that notarization had to be done through [a separate file called `notarize.js`](https://github.com/gravitational/teleport/blob/70d355f90938ac4bb24d9a3ece08f54a59e79e33/web/packages/teleterm/notarize.js) passed to `afterSign`.

Because we don't pass `notarize`, during the tag build electron-builder claims that notarization was not done:

```
• skipped macOS notarization  reason=`notarize` options were not provided
```

This is not true as notarization is done through `notarize.js`, it just doesn't produce any output.

### TODO

- [ ] Use `notarize` field of the macOS target.
- [ ] Remove notarize.js.
- [ ] Remove `electron-notarize` from deps. electron-builder uses `@electron/notarize` now.

---

Related issues:

* https://github.com/gravitational/teleport/issues/14912
