### ISSUE TITLE
VNet (epic)

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#39330]
After Q2, we will balance customer feedback (supporting multiple ports) with expanding to new platforms (Windows, Linux, HTTP apps, etc)

```[tasklist]
### Q3
- [ ] https://github.com/gravitational/teleport/issues/46758
```

```[tasklist]
### Post Q3
- [ ] https://github.com/gravitational/teleport/issues/50849
- [ ] Linux support
- [ ] HTTP apps
- [ ] https://github.com/gravitational/teleport/issues/39507
- [ ] https://github.com/gravitational/teleport/issues/43232
```

```[tasklist]
### Tech debt to address
- [ ] https://github.com/gravitational/teleport/issues/45407
- [ ] We should respect the priority of ordered nameservers in `/etc/resolv.conf` and add a short delay for each one down the list
- [ ] Support `--bootstrap` for `vnet_config` resources
- [ ] Add `vnet_config` to the cache
- [ ] add a default `vnet_config` so `tctl edit vnet_config` works OOTB
- [ ] Steal focus in Connect after successfully installing VNet https://gravitational.slack.com/archives/C03FJA391M3/p1726124228362489?thread_ts=1726075850.091949&cid=C03FJA391M3
- [x] Handling expired certs if user didn't connect to app before cert expiry https://github.com/gravitational/teleport/pull/41031#discussion_r1609684247 https://github.com/gravitational/teleport/pull/41542#discussion_r1618064296
- [ ] https://github.com/gravitational/teleport/issues/48859
```

---

During Q2, we'll focus on getting rid of the repeated password prompt, supporting per-session MFA, and adding more feedback to the UI.

```[tasklist]
### Q2 (Rafal)
- [ ] https://github.com/gravitational/teleport/pull/43746
- [ ] https://github.com/gravitational/teleport/pull/43952
- [x] Detect `SMAppService` support, ~monitor daemon status~
- [ ] https://github.com/gravitational/teleport/pull/44639
- [x] Per-session MFA
- [x] prevent multiple VNet processes from running simultaneously https://github.com/gravitational/teleport/pull/41413#discussion_r1608761833
```

---

At the start of Q2, we'll make the implementation more robust.

```[tasklist]
### Early Q2 (aiming for 16.0) (Nic + Rafal)
- [x] Reuse API clients (Nic) https://github.com/gravitational/teleport/pull/41033
- [x] Support multiple active profiles (Nic) https://github.com/gravitational/teleport/pull/41033
- [x] Support custom DNS zones (Nic) https://github.com/gravitational/teleport/pull/41545
- [ ] https://github.com/gravitational/teleport/pull/41415
- [ ] https://github.com/gravitational/teleport/pull/41587
- [ ] https://github.com/gravitational/teleport/pull/41889
- [x] https://github.com/gravitational/teleport/pull/42550 https://github.com/gravitational/teleport/pull/42846
- [ ] https://github.com/gravitational/teleport/pull/42600
```

---

By the end of Q1 we want to have a fully functional VNet integration in Connect and tsh. VNet itself won't be daemonized yet, so it will prompt for password on each start.

```[tasklist]
### Q1
- [x] Implement `tsh vnet` (without recent connections)
- [x] IPv6 support
- [ ] https://github.com/gravitational/teleport/pull/40526
- [ ] https://github.com/gravitational/teleport/issues/39506
- [ ] https://github.com/gravitational/teleport/pull/40889
- [ ] https://github.com/gravitational/teleport/pull/40893
- [ ] https://github.com/gravitational/teleport/pull/40972
- [ ] https://github.com/gravitational/teleport/pull/41031
- [ ] https://github.com/gravitational/teleport/pull/41032
- [ ] https://github.com/gravitational/teleport/pull/41033
- [ ] https://github.com/gravitational/teleport/pull/41542
- [x] Add `vnet_config` resource
- [ ] https://github.com/gravitational/cloud/pull/8092
- [ ] https://github.com/gravitational/teleport/pull/40995
```

---

We want to provide the design partner with a demo ASAP. It won't have any of the niceties listed in the Q1 list and basically any UI. What's important is that it will let them verify whether the core idea of VNet.

```[tasklist]
### Demo for the design partner
- [x] Support custom DNS zones
- [x] Share the demo by March 29th
```

**Comment by zmb3** [comment]
I'm going to close this tracking issue as we're no longer in "initial launch" mode tracking the must-haves, we're now in "progressive enhancement" mode.
