### ISSUE TITLE
Database Access AWS discovery reliability milestone

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#41004]
- [ ] Document (1 week)
  - [x] Revamp DB discovery guide
    - [x] https://github.com/gravitational/teleport/issues/41354
  - [x] Discovery IAM reference page (or in the same page)
  - [ ] (stretch) https://github.com/gravitational/teleport/issues/38924
  - [ ] (stretch) Document all common deployments (EC2, Helm, ECS)
- [ ] Clear some backlogs (1~3 weeks)
  - [x] https://github.com/gravitational/teleport/issues/38922
  - [ ] https://github.com/gravitational/teleport/issues/16188
  - [ ] https://github.com/gravitational/teleport/issues/43829
  - [ ] (stretch) https://github.com/gravitational/teleport/issues/31097
  - [x] https://github.com/gravitational/teleport/issues/29828
  - [ ] (stretch) https://github.com/gravitational/teleport/issues/38306
- [ ] Web Discovery Flow
  - [x] ECS deployment
    - [x] https://github.com/gravitational/teleport/issues/40787
    - [x] https://github.com/gravitational/teleport/issues/40174
    - [x] https://github.com/gravitational/teleport/issues/40522
    - [x] https://github.com/gravitational/teleport/issues/41255
    - [x] https://github.com/gravitational/teleport.e/issues/3603
  - [ ] (stretch) https://github.com/gravitational/teleport/issues/33477
  - [x] https://github.com/gravitational/teleport/issues/41256
  - [x] #41312

**Comment by greedy52** [comment]
round 1 completed
