### ISSUE TITLE
Discover flow for EC2 using Script installation method

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#41002]
Auto Discovering EC2 instances can use the EICE or the Script mode.
When using the Script mode, teleport uses SSM to send a command to the target instance and that command installs and runs a teleport node agent.
You can read more about it here: https://goteleport.com/docs/auto-discovery/servers/ec2-discovery/

The Discover wizard has support for EC2 Auto Discover using the EICE mode.
This issue will track the required PRs for adding the Script mode.
Here's an overview of the flow:
- User picks `EC2 with SSM (recommended)` tile in `Enroll new resource`
  - This can become the only EC2 tile (if we end up removing the EICE flow)
  - User is notified that only EC2 instances with an SSM Agent will be added
    - IAM Profile for the EC2 instance must include AmazonSSMManagedInstanceCore Policy
    - SSM Agent must be running on the target EC2 instance https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent-status-and-restart.html
- User picks an SSM Document Name (default: `TeleportDiscoveryInstaller`)
- User is presented with a script that they should run in AWS CloudShell
- Self hosted only: User should run a DiscoveryService (DiscoveryGroup as input)
- POST `/webapi/token` to create IAM Join Token ("discover-ec2-iam-token" w/ account/region allow rules)
  - Token name must be used in discovery config below
```yaml
kind: token
spec:
  roles: [Node]
  join_method: iam
  allow:
  - aws_account: <account-id from integration role arn>
```
- POST /DiscoveryConfig is created and flow is completed
```yaml
kind: discovery_config
version: v1
metadata:
  name: my-dc-for-ec2ssm
spec:
  discovery_group: "cloud-discovery-group"
  aws:
    - types: ["ec2"]
      regions: ["eu-west-2"]
      tags:
        "*": "*"
      integration: MyIntegration
      install:
        enroll_mode: 1 # script
        install_teleport: true
        join_token: <token name created above>
      ssm:
        document_name: DOC1
```

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/40937
- [ ] https://github.com/gravitational/teleport/pull/40959
- [ ] https://github.com/gravitational/teleport/pull/41053
- [ ] https://github.com/gravitational/teleport/pull/42038
```

```[tasklist]
### Tasks
```
