### ISSUE TITLE
Teleport Connect: improved terminal experience milestone

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#41068]
This issue tracks the Q2 work of improving Teleport Connect as a general-purpose terminal emulator, particularly on Windows.

- [x] Allow users to specify a shell (wsl, pwsh7, etc)
  - [x] #19392
  - [x] #20186
- [x] Verify PowerShell completion works properly: #21809
- [x] Enable ConPTY: #38087
- [x] Fix copy/paste on Windows:
  - [x] #37650
  - [x] #22828
  - [x] #24451
- [x] Change default (conflicting) keyboard shortcuts on Windows: https://github.com/gravitational/teleport/issues/41207
- [x] Set `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` when launching a shell: #22536
