### ISSUE TITLE
Machine ID: Bot Instance epic

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#41456]
Estimates set on 18th of June.

- [ ] Merging the RFD / Addressing changes - 1 week at most depending on review
- [x] Protos, Backend Service, gRPC service with just List/Get/Delete - @timothyb89 - target 25th june - https://github.com/gravitational/teleport/pull/42899
- [x] Creation of Bot Instance on Join - @timothyb89 - target 3rd july - 1 week - https://github.com/gravitational/teleport/pull/43577
- [x] Heartbeating RPC implementation - @strideynet - half week - https://github.com/gravitational/teleport/pull/42909)
- [x] Add heartbeat submission to tbot - @strideynet - https://github.com/gravitational/teleport/pull/42909
- [x] ~~Refactor existing HTTP and gRPC join methods to support preserving Bot Identity - @timothyb89 - target 17th july - 2 weeks~~ Determined to be unnecessary
- [x] Secure bot reauthentication for all join methods - @timothyb89 - https://github.com/gravitational/teleport/pull/44257
- [x] Update `tbot` to provide existing identity when renewing - @strideynet - 2 weeks - https://github.com/gravitational/teleport/pull/43732
- [x] Move renewal counter to bot instance - @timothyb89 - target 24th july?? - 1 week - https://github.com/gravitational/teleport/pull/44583
- [x] Add BotInstanceID to Audit Events - @strideynet - https://github.com/gravitational/teleport/pull/43786

**Comment by timothyb89** [comment]
Related: https://github.com/gravitational/teleport/issues/26885
