### ISSUE TITLE
AWS OIDC Integration Dashboard

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#41909]
We should give the user the visibility and management tools, so they can understand the current status and fix/change any configuration related to the Integration.
The following components must be part of this dashboard.

### AWS App Access
Whether the AWS App Access is enabled for the integration.
Users should be able to enable or disable the AWS App.
Enabling it will redirect them to the Discover flow.

#### RDS, EC2 and EKS
RDS databases, EC2 instances and EKS clusters can be enrolled and accessed from teleport.

Enrollment is done by creating a new DiscoveryConfig associated with an existing DiscoveryService's DiscoveryGroup (self-hosted users must manage their own DiscoveryService).
The dashboard must show the DiscoveryConfig rules created for each type of resource.

For RDS, the flow deploys a Database Service in user's AWS Account using Amazon ECS.
Users should see how many database agents deployed in ECS exist (name, teleport version, config, ...).

<sub>
Listing ECS Services requires a region. In order to get the region we'll use two sources:
a) regions in use by the DiscoveryConfig rules;
b) regions in use by the onboarded RDS databases
</sub>

## Tasks
Tasks will allow users to see which resources failed to enroll.
When opening the Integration, users should see how many tasks exists and possibly open the Tasks view.

Final design (internal only)
https://www.figma.com/design/v6GunK50D2VC7w7I2FBDNf/Access-(Management)?node-id=4143-2783&node-type=canvas&t=r1DInS5qFyYyH1vw-0

```[tasklist]
### Dashboard
- [ ] https://github.com/gravitational/teleport/pull/42012
- [ ] https://github.com/gravitational/teleport/pull/43861
- [ ] https://github.com/gravitational/teleport/pull/43862
- [ ] https://github.com/gravitational/teleport/pull/44540
- [ ] https://github.com/gravitational/teleport/pull/45553
- [ ] https://github.com/gravitational/teleport/pull/45637
- [ ] https://github.com/gravitational/teleport/pull/48985
- [ ] https://github.com/gravitational/teleport/pull/48986
- [ ] https://github.com/gravitational/teleport/pull/48994
- [ ] https://github.com/gravitational/teleport/pull/48991
- [ ] https://github.com/gravitational/teleport/pull/49325
- [ ] https://github.com/gravitational/teleport/pull/49514
- [ ] https://github.com/gravitational/teleport/pull/49588
- [ ] https://github.com/gravitational/teleport/pull/49331
- [ ] https://github.com/gravitational/teleport/pull/49352
- [ ] https://github.com/gravitational/teleport/pull/50843
- [ ] https://github.com/gravitational/teleport/pull/50433
- [ ] https://github.com/gravitational/teleport/pull/50495
- [ ] https://github.com/gravitational/teleport/pull/51508
- [ ] https://github.com/gravitational/teleport/pull/51489
- [ ] https://github.com/gravitational/teleport/pull/51585
- [ ] https://github.com/gravitational/teleport/pull/51647
```

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/46059
- [ ] https://github.com/gravitational/teleport/pull/46131
- [ ] https://github.com/gravitational/teleport/pull/47062
- [ ] https://github.com/gravitational/teleport/pull/47327
- [ ] https://github.com/gravitational/teleport/pull/47329
- [ ] https://github.com/gravitational/cloud/pull/10703
- [ ] https://github.com/gravitational/teleport/pull/47380
- [ ] https://github.com/gravitational/teleport/pull/47391
- [ ] https://github.com/gravitational/teleport/pull/47064
- [ ] https://github.com/gravitational/teleport/pull/47496
- [ ] https://github.com/gravitational/teleport/pull/50130
- [ ] https://github.com/gravitational/teleport/pull/50855
- [ ] https://github.com/gravitational/teleport/pull/47626
- [ ] https://github.com/gravitational/teleport/pull/47712
- [ ] https://github.com/gravitational/teleport/pull/49887
- [ ] https://github.com/gravitational/teleport/pull/50024
- [ ] https://github.com/gravitational/teleport/pull/47513
- [ ] https://github.com/gravitational/teleport/pull/50377
- [ ] https://github.com/gravitational/teleport/pull/50985
- [ ] https://github.com/gravitational/teleport/pull/50986
- [ ] https://github.com/gravitational/teleport/pull/51018
- [ ] https://github.com/gravitational/teleport/pull/51702
- [ ] https://github.com/gravitational/teleport/pull/52191
- [ ] https://github.com/gravitational/teleport/pull/47556
```

```[tasklist]
### Other UserTask ideas
- [ ] DiscoverEC2: missing SSM document
- [ ] DiscoverEC2: create more IssueTypes based on the error parsed from Failed Script Invocations
- [ ] DiscoverEC2/RDS/EKS: missing permissions
- [ ] Database Access: databases without a matching DatabaseService
- [ ] IntegrationSetup: UserTask for re-creating the IdP if it gets removed (or lacking permissions - use PingRequest)
```

**Comment by zmb3** [comment]
@marcoandredinis are we good to close this one?
