### ISSUE TITLE
Remove S3 fields when setting up the AWS OIDC Integration

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#44053]
See Amazon blog post about the change
https://aws.amazon.com/about-aws/whats-new/2024/07/aws-identity-access-management-open-id-connect-identity-providers/

What would you like Teleport to do?
Amazon no longer requires thumbprint if the issuer's certificate is signed by a trusted root certificate authority.
Let's remove all things related to setting up the issuer using an S3 bucket.

What problem does this solve?
Teleport should not present an alternative way of setting up the Integration, which is way more complex and requires public buckets (not every aws account allows it).

If a workaround exists, please include it.
Go to the Integration in the UI and remove the S3 location fields.
You'll get a new shell script that you should run and that will
You can also remove the s3 bucket/objects because they are no longer needed.

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/44057
- [ ] https://github.com/gravitational/teleport/pull/44058
- [ ] https://github.com/gravitational/teleport/pull/44104
- [ ] https://github.com/gravitational/teleport/pull/44507
```

Fixes:
https://github.com/gravitational/teleport/issues/40366
https://github.com/gravitational/teleport/issues/40794

**Comment by zmb3** [comment]
@marcoandredinis is this good to close?
