### ISSUE TITLE
Teleport Connect tab with CLI database client hangs if client is not found

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#44385]
Connect used to show an error when the client was not found:

<img width="1280" alt="not-found" src="https://github.com/user-attachments/assets/cc10f755-4c25-4402-a28d-1487aeb2ef60">

However, since the upgrade of node-pty from 0.11.0-beta29 to 1.1.0-beta5 (#35776), this has stopped working and the terminal tab just hangs instead. The shared process emits the following logs:

```
[PtyHostService] info: created PTY process for id yPSubDwNjMM-_PQWatzVw
[PtyProcess (id: yPSubDwNjMM-_PQWatzVw psql postgres://dba_readonly@localhost:58981/postgres)] info: status -> open
[PtyEventsStreamHandler (id: yPSubDwNjMM-_PQWatzVw)] info: stream has started
[PtyProcess (id: yPSubDwNjMM-_PQWatzVw psql postgres://dba_readonly@localhost:58981/postgres)] info: pty has been terminated with exit code: 1
[PtyProcess (id: yPSubDwNjMM-_PQWatzVw psql postgres://dba_readonly@localhost:58981/postgres)] info: status -> terminated
```

```[tasklist]
### Tasks
- [x] Show an error if the CLI db client is not found.
- [x] Add a test to make sure this doesn't break in the future.
- [x] Make sure it works on all three platforms.
```

The error doesn't have to be shown instead of a TTY like in the screenshot above. It can be shown within the TTY itself. It's how it's been working on Linux for quite some time.
