### ISSUE TITLE
Add Enhanced Empty States for Bots and Device Trust Pages

### ISSUE THREAD

**Issue by roraback** [gravitational/teleport#44837]
Add empty states for these two pages that highlight their benefits, modeled after the Access Lists empty state.

Text and image ideas [here](https://docs.google.com/document/d/1s4Vuzoc2REVb7_4ss_mFpuJTDE23XD1n9Is7j1v8gG0/edit?usp=sharing)
```[tasklist]
### Tasks
- [x] High Fidelity Design
- [x] Feature Content Finalization
- [x] Feature Images Creation
```

**Comment by rishibarbhaya-design** [comment]
Based on the overall requirements, we (me and @roraback).
We have landed on some conclusion pointers.
- Implement empty states following the similar structure of Access Requests
- For features content, @klizhentas has added pointers. Please take a look at the [document for content](https://docs.google.com/document/d/1s4Vuzoc2REVb7_4ss_mFpuJTDE23XD1n9Is7j1v8gG0/edit?usp=sharing).
- Use product images or explanatory images instead of illustrations.

For Design refer to this [Figma link](https://www.figma.com/design/v6GunK50D2VC7w7I2FBDNf/Management?node-id=4302-40110&t=rNSuulYGugrD3RYT-1).

**What's Done?**

- High Fidelity Design (page structure)
- Feature Content

**What's Next?**

- Brainstorm design ideas for each feature with @strideynet 
- Reuse or create new images as per planning 
- ETA for Images in the next 4-5 days

**Conclusion**

- We should implement empty states for any other feature/module. Lack of empty states is part of the poor user experience and does not give an idea to the user what a particular feature does.
- Follow the similar structure for any other empty state across the product. 
- Suggestion to create a dedicated component for the empty states to reuse.

**Comment by rishibarbhaya-design** [comment]
From all the resources provided, we have designed a base structure and images for the same.
To refer to designs, click on this [Figma Design Link](https://www.figma.com/design/v6GunK50D2VC7w7I2FBDNf/Management?node-id=4302-40110&t=5koncBHAILO85TEb-1)

In the next step, @avatus will be implementing the designs.

**Comment by avatus** [comment]
Bots: https://github.com/gravitational/teleport/pull/46773
Devices: https://github.com/gravitational/teleport.e/pull/5090
