### ISSUE TITLE
Health check the AWS OIDC Integration before saving it

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#45703]
What would you like Teleport to do?
When creating a new AWS OIDC Integration, if something is not correctly set up, the user must be warned about it.

What problem does this solve?
If the integration is not correctly set up, users are only aware of it much later, when using a specific feature.
Eg, when the cluster is not publicly accessible, the user sets up the integration and only finds out that it is not working when they try to use any feature that depends on it (eg, auto-enroll ec2 instances)

If a workaround exists, please include it.
```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/45702
- [x] Web: call `/ping` endpoint after updating the integration and go back to editing it if it returns an error
- [x] Web: call `/ping` endpoint after creating the integration and go back to editing if it returns an error
- [x] Web: call `/ping` endpoint after selecting an integration from discover flows (prevent user from going next if it fails)
```
