### ISSUE TITLE
Multi-port TCP app access

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#46758]
[RFD](https://github.com/gravitational/teleport/blob/master/rfd/0182-multi-port-tcp-app-access.md)

```[tasklist]
### Tasks
- [ ] https://github.com/gravitational/teleport/pull/47706
- [ ] https://github.com/gravitational/teleport/pull/49047
- [ ] https://github.com/gravitational/teleport/pull/49453
- [ ] https://github.com/gravitational/teleport/pull/49688
- [ ] https://github.com/gravitational/teleport/pull/49944
- [ ] https://github.com/gravitational/teleport/pull/50008
- [ ] https://github.com/gravitational/teleport/pull/50216
```

The tasks above allow the design partner to evaluate multi-port TCP app access by using it through VNet. We want to ship those changes first and then do some follow-up tasks.

```[tasklist]
### Follow-ups
- [ ] https://github.com/gravitational/teleport/pull/50429
- [ ] https://github.com/gravitational/teleport/pull/50912
- [ ] https://github.com/gravitational/teleport/pull/50982
- [ ] https://github.com/gravitational/teleport/pull/51016
- [ ] https://github.com/gravitational/teleport/pull/51111
```
