### ISSUE TITLE
5.0 Pre-release Checklist

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4959]
### Pre-release Checklist

This checklist is to be run prior to cutting a release.

- [x] Collaborate on changelog/release notes
- [x] Share release notes and timing with marketing team
- [x] Check Apple Developer Portal to confirm any outstanding T&Cs
