### ISSUE TITLE
API cleanup

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#6393]
**Description**

Clean up several issues in the API package that may confuse clients, lead to issues/bugs, or clutter the code base.

- [x] Improve client version handling: outlined in #6764
- [x] Validation consistency/clarity: Detailed and partially completed in draft PR - #5958
    - Server validation can also be improved by wrapping types in `lib/services` and adding service only methods such as `Validate()` - bit of a bigger refactor but worth metioning.
- [x] Remove aliases: Remove type aliases used for transitioning to new API, such as [this](https://github.com/gravitational/teleport/blob/branch/v6.1/lib/services/types.go). - #6983
- [x] Improve/add tests: Improve client tests (especially around credentials) using a mock server. Add tests for some other sections, such as profile read/write - #6233
- [x] Reorganize package structure: Too many files are now in the main client directory and should be split into more subpackages. This will fix:
    - poor code organization, which will only grow as an issue.
    - poor [godoc](https://pkg.go.dev/github.com/gravitational/teleport/api@v0.0.0-20210304221830-6d8f77815793/client) navigability - #5466 
- [x] Update [RFD 10](https://github.com/gravitational/teleport/blob/master/rfd/0010-api.md) in accordance with [RFD guidelines](https://github.com/gravitational/teleport/blob/master/rfd/0000-rfds.md) - in review #6764
- [ ] Fix various small issues (if time allows):
    - `client.CreateAccessRequest` will fail if the access_request doesn't have it's id set to a uuid from the client side. This uuid should be generated on the server side instead - (#5432 needs update but partially addresses this)
    - some of the older client methods still don't take a ctx, such as `GetUser`
