### ISSUE TITLE
[v6.2+] Edit Pass

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#6943]
Issue for tracking 6.2:

- Improve Readability scores.
- Correct minor things like typos, grammar, punctuation all at once.
- Use the agreed-upon layout conventions for 6.2+.
   - Will try to add tiles where appropriate.
   - Will add some Admonitions too.
- SEO improvements.
- Support easier copy-pasting from examples.
   - Not everyone uses Bash (ZSH is the default on Mac now).
   - Drop using `$` since it doesn't indicate the root user which is required for many operations.
   - Drop using `$` since it prevents easy copy-pasting.
   - Correcting `bsh` code blocks that don't render `bash` code correctly.
- Correct links changed 5/18+.
- Each Edit Pass PR is branched off the previous one so they can be merged into the same Feature Branch then merged all at once into master/main, or merged one at a time into master/main.

Status by section:

- [x] Home - https://github.com/gravitational/teleport/pull/6942
- [x] Server Access - https://github.com/gravitational/teleport/pull/6942
- [x] Application Access - https://github.com/gravitational/teleport/pull/6968
- [x] Kubernetes Access + new Helm docs - https://github.com/gravitational/teleport/pull/7006
- [x] Database Access - https://github.com/gravitational/teleport/pull/7007
- [x] Access Controls - https://github.com/gravitational/teleport/pull/6974
- [x] Preview - https://github.com/gravitational/teleport/pull/6974
- [x] Infrastructure Guides - https://github.com/gravitational/teleport/pull/7018
- [x] Teleport Enterprise - https://github.com/gravitational/teleport/pull/7018
- [x] Cloud - https://github.com/gravitational/teleport/pull/7007
- [x] Architecture - https://github.com/gravitational/teleport/pull/6999
- [x] Advanced Features - https://github.com/gravitational/teleport/pull/6995
- [x] Reference - https://github.com/gravitational/teleport/pull/6961

Other items:

- [x] Remove hard-coded join tokens https://github.com/gravitational/teleport/issues/7086
- [x] Correct branding for Open-Source Edition - https://github.com/gravitational/teleport/pull/6942
- [x] Correct TTL to short-lived certs - Issue https://github.com/gravitational/teleport/issues/5978  - https://github.com/gravitational/teleport/pull/6942 - Server certs and plugin certs (like db access) - this should be `1-10h` for client certificates and `3 months` or `2190h` for DB
- [x] Correct BASH examples - https://github.com/gravitational/teleport/pull/6961 - don't comment but add a UI note `{/* Convert to new UI component https://github.com/gravitational/next/issues/275 */}`.
- [x] Correct branding for Access Plane - https://github.com/gravitational/teleport/pull/6961
- [x] Duplicate entries in Metrics Log - Issue https://github.com/gravitational/teleport/issues/6919 - https://github.com/gravitational/teleport/pull/6974
- [x] Update FAQ per https://github.com/gravitational/teleport/issues/4633 - https://github.com/gravitational/teleport/pull/6974
- [x] Remove duplicate articles - https://github.com/gravitational/teleport/pull/6974
- [x] Adds Tiles to Guide pages and Intro pages for each section, etc.
- [x] Add `sudo` with Admonition along with Bash example changes per the above https://github.com/gravitational/teleport/pull/6603 - slight change here we will only add this for `teleport start` and `teleport configure` commands since these are the only ones that explicitly require this.
- [x] Forward port of https://github.com/gravitational/teleport/pull/6991 - https://github.com/gravitational/teleport/pull/6995
- [x] Verify forward port of https://github.com/gravitational/teleport/pull/6565 - https://github.com/gravitational/teleport/pull/7006
- [x] Drop references to Teleport versions > 2 major versions old - https://github.com/gravitational/teleport/pull/6995
- [x] Better handling of permissions in examples per the above https://github.com/gravitational/teleport/issues/5128
- [x] Backport of https://github.com/gravitational/teleport/pull/6809 - https://github.com/gravitational/teleport/pull/6974

Last-minute additions (identified during PR reviews):

- [x] Update Teleport Node roles/types https://github.com/gravitational/teleport/issues/7147 - https://github.com/gravitational/teleport/pull/6961
- [x] Provide default user roles https://github.com/gravitational/teleport/issues/7062 - https://github.com/gravitational/teleport/pull/6968
- [x] Correct config note https://github.com/gravitational/teleport/issues/6807 - https://github.com/gravitational/teleport/pull/6961
- [x] Backup your config warnings - https://github.com/gravitational/teleport/pull/6968
- [x] Tweaks to PoLP, Sudo, etc. warning. - https://github.com/gravitational/teleport/pull/6968
- [x] TOC-less Guide sections that remove H1 headings (looks cleaner, showcases the new tiles)
- [x] Some errata to commands and steps, commands that will be further improved with the Refresh/validation pass (which is much narrower in focus).
- [x] Correct the minimum tsh client to 3.0.0 - https://github.com/gravitational/teleport/pull/6974
