### ISSUE TITLE
Desktop Access: performance tracking issue

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#9707]
```[tasklist]
# 12.0
- [x] Encode PNGs in Rust
- [x] Ensure that there is no performance penalty related to session recording when recording is not enabled
```

```[tasklist]
# Other
- [ ] Performance improvements RFD
- [ ] Bitmap Caching 
- [ ] https://github.com/gravitational/teleport/issues/17487
```

**Comment by zmb3** [comment]
RDP protocol-level optimizations to investigate:

- [Fast path](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/000966f4-4863-4668-9c13-852e252bb376) parsing: bypasses some of the encapsulation, resulting in less data over the wire and quicker parsing
- RDP 4/5 [compression](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/896fc95d-640a-4e86-8d6b-2faeda3b0919) (only RDP 4, 8K compression currently supported)
- RDP 6/6.1 [bulk compression](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/b876423f-2099-41eb-8f4c-4dbfe19312cd)
- RDP [bitmap caching](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/2bf92588-42bd-4527-8b3e-b90c56e292d2) (could implement at desktop service or extend to browser)
- [RemoteFX Codec](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdprfx/62495a4a-a495-46ea-b459-5cde04c44549): a lossy codec extension that provides efficient and effective compression

**Comment by RyanCode** [comment]
> RDP protocol-level optimizations to investigate:
> 
> * [Fast path](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/000966f4-4863-4668-9c13-852e252bb376) parsing: bypasses some of the encapsulation, resulting in less data over the wire and quicker parsing
> * RDP 4/5 [compression](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/896fc95d-640a-4e86-8d6b-2faeda3b0919) (only RDP 4, 8K compression currently supported)
> * RDP 6/6.1 [bulk compression](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/b876423f-2099-41eb-8f4c-4dbfe19312cd)
> * RDP [bitmap caching](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpegdi/2bf92588-42bd-4527-8b3e-b90c56e292d2) (could implement at desktop service or extend to browser)
> * [RemoteFX Codec](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdprfx/62495a4a-a495-46ea-b459-5cde04c44549): a lossy codec extension that provides efficient and effective compression

which TODO is being implemented.I encode frame on rust side,may I commit a pr?

**Comment by RyanCode** [comment]
Why not implement GDI?
```
The Remote Desktop Protocol: GDI Acceleration Extension aims to reduce the 
bandwidth associated with graphics remoting by encoding the drawing operations 
that produce an image instead of encoding the actual image. 
```

**Comment by RyanCode** [comment]
how's the progress
